// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/grade/grade.proto

package grade

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Добавить в конец message определений
type SetBlockingCriteriaMarkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        int32                  `protobuf:"varint,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	CriterionId   int32                  `protobuf:"varint,2,opt,name=criterion_id,json=criterionId,proto3" json:"criterion_id,omitempty"`
	Mark          float32                `protobuf:"fixed32,3,opt,name=mark,proto3" json:"mark,omitempty"` // 0.0 или 1.0
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBlockingCriteriaMarkRequest) Reset() {
	*x = SetBlockingCriteriaMarkRequest{}
	mi := &file_proto_grade_grade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBlockingCriteriaMarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBlockingCriteriaMarkRequest) ProtoMessage() {}

func (x *SetBlockingCriteriaMarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grade_grade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBlockingCriteriaMarkRequest.ProtoReflect.Descriptor instead.
func (*SetBlockingCriteriaMarkRequest) Descriptor() ([]byte, []int) {
	return file_proto_grade_grade_proto_rawDescGZIP(), []int{0}
}

func (x *SetBlockingCriteriaMarkRequest) GetWorkId() int32 {
	if x != nil {
		return x.WorkId
	}
	return 0
}

func (x *SetBlockingCriteriaMarkRequest) GetCriterionId() int32 {
	if x != nil {
		return x.CriterionId
	}
	return 0
}

func (x *SetBlockingCriteriaMarkRequest) GetMark() float32 {
	if x != nil {
		return x.Mark
	}
	return 0
}

func (x *SetBlockingCriteriaMarkRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type SetBlockingCriteriaMarkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBlockingCriteriaMarkResponse) Reset() {
	*x = SetBlockingCriteriaMarkResponse{}
	mi := &file_proto_grade_grade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBlockingCriteriaMarkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBlockingCriteriaMarkResponse) ProtoMessage() {}

func (x *SetBlockingCriteriaMarkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grade_grade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBlockingCriteriaMarkResponse.ProtoReflect.Descriptor instead.
func (*SetBlockingCriteriaMarkResponse) Descriptor() ([]byte, []int) {
	return file_proto_grade_grade_proto_rawDescGZIP(), []int{1}
}

func (x *SetBlockingCriteriaMarkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetMainCriteriaMarkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        int32                  `protobuf:"varint,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	CriterionId   int32                  `protobuf:"varint,2,opt,name=criterion_id,json=criterionId,proto3" json:"criterion_id,omitempty"`
	Mark          float32                `protobuf:"fixed32,3,opt,name=mark,proto3" json:"mark,omitempty"` // 0.0, 0.25, 0.50, 0.75, 1.00
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMainCriteriaMarkRequest) Reset() {
	*x = SetMainCriteriaMarkRequest{}
	mi := &file_proto_grade_grade_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMainCriteriaMarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMainCriteriaMarkRequest) ProtoMessage() {}

func (x *SetMainCriteriaMarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grade_grade_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMainCriteriaMarkRequest.ProtoReflect.Descriptor instead.
func (*SetMainCriteriaMarkRequest) Descriptor() ([]byte, []int) {
	return file_proto_grade_grade_proto_rawDescGZIP(), []int{2}
}

func (x *SetMainCriteriaMarkRequest) GetWorkId() int32 {
	if x != nil {
		return x.WorkId
	}
	return 0
}

func (x *SetMainCriteriaMarkRequest) GetCriterionId() int32 {
	if x != nil {
		return x.CriterionId
	}
	return 0
}

func (x *SetMainCriteriaMarkRequest) GetMark() float32 {
	if x != nil {
		return x.Mark
	}
	return 0
}

func (x *SetMainCriteriaMarkRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type SetMainCriteriaMarkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMainCriteriaMarkResponse) Reset() {
	*x = SetMainCriteriaMarkResponse{}
	mi := &file_proto_grade_grade_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMainCriteriaMarkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMainCriteriaMarkResponse) ProtoMessage() {}

func (x *SetMainCriteriaMarkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grade_grade_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMainCriteriaMarkResponse.ProtoReflect.Descriptor instead.
func (*SetMainCriteriaMarkResponse) Descriptor() ([]byte, []int) {
	return file_proto_grade_grade_proto_rawDescGZIP(), []int{3}
}

func (x *SetMainCriteriaMarkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_grade_grade_proto protoreflect.FileDescriptor

const file_proto_grade_grade_proto_rawDesc = "" +
	"\n" +
	"\x17proto/grade/grade.proto\x12\x05grade\"\x8a\x01\n" +
	"\x1eSetBlockingCriteriaMarkRequest\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\x05R\x06workId\x12!\n" +
	"\fcriterion_id\x18\x02 \x01(\x05R\vcriterionId\x12\x12\n" +
	"\x04mark\x18\x03 \x01(\x02R\x04mark\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"7\n" +
	"\x1fSetBlockingCriteriaMarkResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x86\x01\n" +
	"\x1aSetMainCriteriaMarkRequest\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\x05R\x06workId\x12!\n" +
	"\fcriterion_id\x18\x02 \x01(\x05R\vcriterionId\x12\x12\n" +
	"\x04mark\x18\x03 \x01(\x02R\x04mark\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"3\n" +
	"\x1bSetMainCriteriaMarkResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\xdc\x01\n" +
	"\x0eGradingService\x12j\n" +
	"\x17SetBlockingCriteriaMark\x12%.grade.SetBlockingCriteriaMarkRequest\x1a&.grade.SetBlockingCriteriaMarkResponse\"\x00\x12^\n" +
	"\x13SetMainCriteriaMark\x12!.grade.SetMainCriteriaMarkRequest\x1a\".grade.SetMainCriteriaMarkResponse\"\x00B\x15Z\x13./proto/grade;gradeb\x06proto3"

var (
	file_proto_grade_grade_proto_rawDescOnce sync.Once
	file_proto_grade_grade_proto_rawDescData []byte
)

func file_proto_grade_grade_proto_rawDescGZIP() []byte {
	file_proto_grade_grade_proto_rawDescOnce.Do(func() {
		file_proto_grade_grade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_grade_grade_proto_rawDesc), len(file_proto_grade_grade_proto_rawDesc)))
	})
	return file_proto_grade_grade_proto_rawDescData
}

var file_proto_grade_grade_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_grade_grade_proto_goTypes = []any{
	(*SetBlockingCriteriaMarkRequest)(nil),  // 0: grade.SetBlockingCriteriaMarkRequest
	(*SetBlockingCriteriaMarkResponse)(nil), // 1: grade.SetBlockingCriteriaMarkResponse
	(*SetMainCriteriaMarkRequest)(nil),      // 2: grade.SetMainCriteriaMarkRequest
	(*SetMainCriteriaMarkResponse)(nil),     // 3: grade.SetMainCriteriaMarkResponse
}
var file_proto_grade_grade_proto_depIdxs = []int32{
	0, // 0: grade.GradingService.SetBlockingCriteriaMark:input_type -> grade.SetBlockingCriteriaMarkRequest
	2, // 1: grade.GradingService.SetMainCriteriaMark:input_type -> grade.SetMainCriteriaMarkRequest
	1, // 2: grade.GradingService.SetBlockingCriteriaMark:output_type -> grade.SetBlockingCriteriaMarkResponse
	3, // 3: grade.GradingService.SetMainCriteriaMark:output_type -> grade.SetMainCriteriaMarkResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_grade_grade_proto_init() }
func file_proto_grade_grade_proto_init() {
	if File_proto_grade_grade_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_grade_grade_proto_rawDesc), len(file_proto_grade_grade_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_grade_grade_proto_goTypes,
		DependencyIndexes: file_proto_grade_grade_proto_depIdxs,
		MessageInfos:      file_proto_grade_grade_proto_msgTypes,
	}.Build()
	File_proto_grade_grade_proto = out.File
	file_proto_grade_grade_proto_goTypes = nil
	file_proto_grade_grade_proto_depIdxs = nil
}
