version: '3.8'

services:
  userservice:
    build:
      context: .
      dockerfile: ./cmd/userservice/Dockerfile
    ports:
      - "50051:50051"
    environment:
      - DB_HOST=rubrlocal  # Замените на IP или имя хоста вашего сервера (например, 192.168.1.100)
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=rubrlocal

  fyne-client:
    build:
      context: .
      dockerfile: ./cmd/fyne-client/Dockerfile
    depends_on:
      - userservice
    networks:
      - rubric-net

networks:
  rubric-net:
    driver: bridge