version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    user: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rubric_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "rubric_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate:v4.15.2
    volumes:
      - ./internal/db/postgres/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://user:password@postgres:5432/rubric_db?sslmode=disable", "up"]
    depends_on:
      postgres:
        condition: service_healthy

  apigateway:
    build:
      context: ./cmd/apigateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - userservice
      - workservice
      - rubricservice
      - gradingservice
      - workassignmentservice
      - notificationservice
      - superaccservice
    environment:
      - GRPC_USERSERVICE_ADDR=userservice:50051
      - GRPC_WORKSERVICE_ADDR=workservice:50052
      - GRPC_RUBRICSERVICE_ADDR=rubricservice:50053
      - GRPC_GRADINGSERVICE_ADDR=gradingservice:50054
      - GRPC_WORKASSIGNMENTSERVICE_ADDR=workassignmentservice:50055
      - GRPC_NOTIFICATIONSERVICE_ADDR=notificationservice:50056
      - GRPC_SUPERACCSERVICE_ADDR=superaccservice:50057

  userservice:
    build:
      context: ./cmd/userservice
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=rubric_db

  workservice:
    build:
      context: ./cmd/workservice
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=rubric_db

  rubricservice:
    build:
      context: ./cmd/rubricservice
      dockerfile: Dockerfile
    ports:
      - "50053:50053"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=rubric_db

  gradingservice:
    build:
      context: ./cmd/gradingservice
      dockerfile: Dockerfile
    ports:
      - "50054:50054"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=rubric_db

  workassignmentservice:
    build:
      context: ./cmd/workassignmentservice
      dockerfile: Dockerfile
    ports:
      - "50055:50055"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=rubric_db

  notificationservice:
    build:
      context: ./cmd/notificationservice
      dockerfile: Dockerfile
    ports:
      - "50056:50056"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=rubric_db

  superaccservice:
    build:
      context: ./cmd/superaccservice
      dockerfile: Dockerfile
    ports:
      - "50057:50057"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=rubric_db

volumes:
  postgres-data: