// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/superacc.proto

package superacc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_proto_superacc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_superacc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_superacc_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateRoleRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UpdateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleResponse) Reset() {
	*x = UpdateRoleResponse{}
	mi := &file_proto_superacc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleResponse) ProtoMessage() {}

func (x *UpdateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_superacc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_superacc_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateRoleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ManageGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageGroupRequest) Reset() {
	*x = ManageGroupRequest{}
	mi := &file_proto_superacc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageGroupRequest) ProtoMessage() {}

func (x *ManageGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_superacc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageGroupRequest.ProtoReflect.Descriptor instead.
func (*ManageGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_superacc_proto_rawDescGZIP(), []int{2}
}

func (x *ManageGroupRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ManageGroupRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ManageGroupRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ManageGroupRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ManageGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageGroupResponse) Reset() {
	*x = ManageGroupResponse{}
	mi := &file_proto_superacc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageGroupResponse) ProtoMessage() {}

func (x *ManageGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_superacc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageGroupResponse.ProtoReflect.Descriptor instead.
func (*ManageGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_superacc_proto_rawDescGZIP(), []int{3}
}

func (x *ManageGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ManageGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ManageDisciplineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisciplineId  int32                  `protobuf:"varint,1,opt,name=discipline_id,json=disciplineId,proto3" json:"discipline_id,omitempty"`
	GroupId       int32                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	SeminaristId  int32                  `protobuf:"varint,3,opt,name=seminarist_id,json=seminaristId,proto3" json:"seminarist_id,omitempty"`
	AssistantId   int32                  `protobuf:"varint,4,opt,name=assistant_id,json=assistantId,proto3" json:"assistant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageDisciplineRequest) Reset() {
	*x = ManageDisciplineRequest{}
	mi := &file_proto_superacc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageDisciplineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageDisciplineRequest) ProtoMessage() {}

func (x *ManageDisciplineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_superacc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageDisciplineRequest.ProtoReflect.Descriptor instead.
func (*ManageDisciplineRequest) Descriptor() ([]byte, []int) {
	return file_proto_superacc_proto_rawDescGZIP(), []int{4}
}

func (x *ManageDisciplineRequest) GetDisciplineId() int32 {
	if x != nil {
		return x.DisciplineId
	}
	return 0
}

func (x *ManageDisciplineRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ManageDisciplineRequest) GetSeminaristId() int32 {
	if x != nil {
		return x.SeminaristId
	}
	return 0
}

func (x *ManageDisciplineRequest) GetAssistantId() int32 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

type ManageDisciplineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageDisciplineResponse) Reset() {
	*x = ManageDisciplineResponse{}
	mi := &file_proto_superacc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageDisciplineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageDisciplineResponse) ProtoMessage() {}

func (x *ManageDisciplineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_superacc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageDisciplineResponse.ProtoReflect.Descriptor instead.
func (*ManageDisciplineResponse) Descriptor() ([]byte, []int) {
	return file_proto_superacc_proto_rawDescGZIP(), []int{5}
}

func (x *ManageDisciplineResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ManageDisciplineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_superacc_proto protoreflect.FileDescriptor

const file_proto_superacc_proto_rawDesc = "" +
	"\n" +
	"\x14proto/superacc.proto\x12\bsuperacc\"@\n" +
	"\x11UpdateRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"H\n" +
	"\x12UpdateRoleResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"t\n" +
	"\x12ManageGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"I\n" +
	"\x13ManageGroupResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\xa1\x01\n" +
	"\x17ManageDisciplineRequest\x12#\n" +
	"\rdiscipline_id\x18\x01 \x01(\x05R\fdisciplineId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x05R\agroupId\x12#\n" +
	"\rseminarist_id\x18\x03 \x01(\x05R\fseminaristId\x12!\n" +
	"\fassistant_id\x18\x04 \x01(\x05R\vassistantId\"N\n" +
	"\x18ManageDisciplineResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2\x8b\x02\n" +
	"\x0fSuperAccService\x12M\n" +
	"\x0eUpdateUserRole\x12\x1b.superacc.UpdateRoleRequest\x1a\x1c.superacc.UpdateRoleResponse\"\x00\x12L\n" +
	"\vManageGroup\x12\x1c.superacc.ManageGroupRequest\x1a\x1d.superacc.ManageGroupResponse\"\x00\x12[\n" +
	"\x10ManageDiscipline\x12!.superacc.ManageDisciplineRequest\x1a\".superacc.ManageDisciplineResponse\"\x00B\x12Z\x10./proto;superaccb\x06proto3"

var (
	file_proto_superacc_proto_rawDescOnce sync.Once
	file_proto_superacc_proto_rawDescData []byte
)

func file_proto_superacc_proto_rawDescGZIP() []byte {
	file_proto_superacc_proto_rawDescOnce.Do(func() {
		file_proto_superacc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_superacc_proto_rawDesc), len(file_proto_superacc_proto_rawDesc)))
	})
	return file_proto_superacc_proto_rawDescData
}

var file_proto_superacc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_superacc_proto_goTypes = []any{
	(*UpdateRoleRequest)(nil),        // 0: superacc.UpdateRoleRequest
	(*UpdateRoleResponse)(nil),       // 1: superacc.UpdateRoleResponse
	(*ManageGroupRequest)(nil),       // 2: superacc.ManageGroupRequest
	(*ManageGroupResponse)(nil),      // 3: superacc.ManageGroupResponse
	(*ManageDisciplineRequest)(nil),  // 4: superacc.ManageDisciplineRequest
	(*ManageDisciplineResponse)(nil), // 5: superacc.ManageDisciplineResponse
}
var file_proto_superacc_proto_depIdxs = []int32{
	0, // 0: superacc.SuperAccService.UpdateUserRole:input_type -> superacc.UpdateRoleRequest
	2, // 1: superacc.SuperAccService.ManageGroup:input_type -> superacc.ManageGroupRequest
	4, // 2: superacc.SuperAccService.ManageDiscipline:input_type -> superacc.ManageDisciplineRequest
	1, // 3: superacc.SuperAccService.UpdateUserRole:output_type -> superacc.UpdateRoleResponse
	3, // 4: superacc.SuperAccService.ManageGroup:output_type -> superacc.ManageGroupResponse
	5, // 5: superacc.SuperAccService.ManageDiscipline:output_type -> superacc.ManageDisciplineResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_superacc_proto_init() }
func file_proto_superacc_proto_init() {
	if File_proto_superacc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_superacc_proto_rawDesc), len(file_proto_superacc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_superacc_proto_goTypes,
		DependencyIndexes: file_proto_superacc_proto_depIdxs,
		MessageInfos:      file_proto_superacc_proto_msgTypes,
	}.Build()
	File_proto_superacc_proto = out.File
	file_proto_superacc_proto_goTypes = nil
	file_proto_superacc_proto_depIdxs = nil
}
