// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/work/work.proto

package work

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTasksForSeminaristRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeminaristId  string                 `protobuf:"bytes,1,opt,name=seminarist_id,json=seminaristId,proto3" json:"seminarist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksForSeminaristRequest) Reset() {
	*x = GetTasksForSeminaristRequest{}
	mi := &file_proto_work_work_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksForSeminaristRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksForSeminaristRequest) ProtoMessage() {}

func (x *GetTasksForSeminaristRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksForSeminaristRequest.ProtoReflect.Descriptor instead.
func (*GetTasksForSeminaristRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{0}
}

func (x *GetTasksForSeminaristRequest) GetSeminaristId() string {
	if x != nil {
		return x.SeminaristId
	}
	return ""
}

type GetTasksForSeminaristResponse struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Tasks         []*GetTasksForSeminaristResponse_Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Error         string                                `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksForSeminaristResponse) Reset() {
	*x = GetTasksForSeminaristResponse{}
	mi := &file_proto_work_work_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksForSeminaristResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksForSeminaristResponse) ProtoMessage() {}

func (x *GetTasksForSeminaristResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksForSeminaristResponse.ProtoReflect.Descriptor instead.
func (*GetTasksForSeminaristResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{1}
}

func (x *GetTasksForSeminaristResponse) GetTasks() []*GetTasksForSeminaristResponse_Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *GetTasksForSeminaristResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetStudentWorksForSeminaristRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeminaristId  string                 `protobuf:"bytes,1,opt,name=seminarist_id,json=seminaristId,proto3" json:"seminarist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentWorksForSeminaristRequest) Reset() {
	*x = GetStudentWorksForSeminaristRequest{}
	mi := &file_proto_work_work_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentWorksForSeminaristRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentWorksForSeminaristRequest) ProtoMessage() {}

func (x *GetStudentWorksForSeminaristRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentWorksForSeminaristRequest.ProtoReflect.Descriptor instead.
func (*GetStudentWorksForSeminaristRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{2}
}

func (x *GetStudentWorksForSeminaristRequest) GetSeminaristId() string {
	if x != nil {
		return x.SeminaristId
	}
	return ""
}

type GetStudentWorksForSeminaristResponse struct {
	state         protoimpl.MessageState                              `protogen:"open.v1"`
	Works         []*GetStudentWorksForSeminaristResponse_StudentWork `protobuf:"bytes,1,rep,name=works,proto3" json:"works,omitempty"`
	Error         string                                              `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentWorksForSeminaristResponse) Reset() {
	*x = GetStudentWorksForSeminaristResponse{}
	mi := &file_proto_work_work_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentWorksForSeminaristResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentWorksForSeminaristResponse) ProtoMessage() {}

func (x *GetStudentWorksForSeminaristResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentWorksForSeminaristResponse.ProtoReflect.Descriptor instead.
func (*GetStudentWorksForSeminaristResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{3}
}

func (x *GetStudentWorksForSeminaristResponse) GetWorks() []*GetStudentWorksForSeminaristResponse_StudentWork {
	if x != nil {
		return x.Works
	}
	return nil
}

func (x *GetStudentWorksForSeminaristResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetTaskDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskDetailsRequest) Reset() {
	*x = GetTaskDetailsRequest{}
	mi := &file_proto_work_work_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskDetailsRequest) ProtoMessage() {}

func (x *GetTaskDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetTaskDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskDetailsRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type GetTaskDetailsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Title          string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Deadline       string                 `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	GroupName      string                 `protobuf:"bytes,4,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	DisciplineName string                 `protobuf:"bytes,5,opt,name=discipline_name,json=disciplineName,proto3" json:"discipline_name,omitempty"`
	Error          string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTaskDetailsResponse) Reset() {
	*x = GetTaskDetailsResponse{}
	mi := &file_proto_work_work_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskDetailsResponse) ProtoMessage() {}

func (x *GetTaskDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetTaskDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskDetailsResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetTaskDetailsResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetTaskDetailsResponse) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *GetTaskDetailsResponse) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GetTaskDetailsResponse) GetDisciplineName() string {
	if x != nil {
		return x.DisciplineName
	}
	return ""
}

func (x *GetTaskDetailsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateTaskGroupAndDisciplineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	GroupId       int32                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	DisciplineId  int32                  `protobuf:"varint,3,opt,name=discipline_id,json=disciplineId,proto3" json:"discipline_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskGroupAndDisciplineRequest) Reset() {
	*x = UpdateTaskGroupAndDisciplineRequest{}
	mi := &file_proto_work_work_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskGroupAndDisciplineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskGroupAndDisciplineRequest) ProtoMessage() {}

func (x *UpdateTaskGroupAndDisciplineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskGroupAndDisciplineRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskGroupAndDisciplineRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTaskGroupAndDisciplineRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *UpdateTaskGroupAndDisciplineRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UpdateTaskGroupAndDisciplineRequest) GetDisciplineId() int32 {
	if x != nil {
		return x.DisciplineId
	}
	return 0
}

type UpdateTaskGroupAndDisciplineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskGroupAndDisciplineResponse) Reset() {
	*x = UpdateTaskGroupAndDisciplineResponse{}
	mi := &file_proto_work_work_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskGroupAndDisciplineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskGroupAndDisciplineResponse) ProtoMessage() {}

func (x *UpdateTaskGroupAndDisciplineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskGroupAndDisciplineResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskGroupAndDisciplineResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTaskGroupAndDisciplineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateTaskGroupAndDisciplineResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetTasksForLectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LectorId      int32                  `protobuf:"varint,1,opt,name=lector_id,json=lectorId,proto3" json:"lector_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksForLectorRequest) Reset() {
	*x = GetTasksForLectorRequest{}
	mi := &file_proto_work_work_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksForLectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksForLectorRequest) ProtoMessage() {}

func (x *GetTasksForLectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksForLectorRequest.ProtoReflect.Descriptor instead.
func (*GetTasksForLectorRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{8}
}

func (x *GetTasksForLectorRequest) GetLectorId() int32 {
	if x != nil {
		return x.LectorId
	}
	return 0
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Deadline      string                 `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_work_work_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{9}
}

func (x *Task) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

type GetTasksForLectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksForLectorResponse) Reset() {
	*x = GetTasksForLectorResponse{}
	mi := &file_proto_work_work_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksForLectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksForLectorResponse) ProtoMessage() {}

func (x *GetTasksForLectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksForLectorResponse.ProtoReflect.Descriptor instead.
func (*GetTasksForLectorResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{10}
}

func (x *GetTasksForLectorResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *GetTasksForLectorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_proto_work_work_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteTaskRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_proto_work_work_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetTaskTitleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTaskTitleRequest) Reset() {
	*x = SetTaskTitleRequest{}
	mi := &file_proto_work_work_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTaskTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTaskTitleRequest) ProtoMessage() {}

func (x *SetTaskTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTaskTitleRequest.ProtoReflect.Descriptor instead.
func (*SetTaskTitleRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{13}
}

func (x *SetTaskTitleRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *SetTaskTitleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type SetTaskTitleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTaskTitleResponse) Reset() {
	*x = SetTaskTitleResponse{}
	mi := &file_proto_work_work_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTaskTitleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTaskTitleResponse) ProtoMessage() {}

func (x *SetTaskTitleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTaskTitleResponse.ProtoReflect.Descriptor instead.
func (*SetTaskTitleResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{14}
}

func (x *SetTaskTitleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetTaskTitleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetTaskDescriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTaskDescriptionRequest) Reset() {
	*x = SetTaskDescriptionRequest{}
	mi := &file_proto_work_work_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTaskDescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTaskDescriptionRequest) ProtoMessage() {}

func (x *SetTaskDescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTaskDescriptionRequest.ProtoReflect.Descriptor instead.
func (*SetTaskDescriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{15}
}

func (x *SetTaskDescriptionRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *SetTaskDescriptionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SetTaskDescriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTaskDescriptionResponse) Reset() {
	*x = SetTaskDescriptionResponse{}
	mi := &file_proto_work_work_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTaskDescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTaskDescriptionResponse) ProtoMessage() {}

func (x *SetTaskDescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTaskDescriptionResponse.ProtoReflect.Descriptor instead.
func (*SetTaskDescriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{16}
}

func (x *SetTaskDescriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetTaskDescriptionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetTaskDeadlineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Deadline      string                 `protobuf:"bytes,2,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTaskDeadlineRequest) Reset() {
	*x = SetTaskDeadlineRequest{}
	mi := &file_proto_work_work_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTaskDeadlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTaskDeadlineRequest) ProtoMessage() {}

func (x *SetTaskDeadlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTaskDeadlineRequest.ProtoReflect.Descriptor instead.
func (*SetTaskDeadlineRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{17}
}

func (x *SetTaskDeadlineRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *SetTaskDeadlineRequest) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

type SetTaskDeadlineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTaskDeadlineResponse) Reset() {
	*x = SetTaskDeadlineResponse{}
	mi := &file_proto_work_work_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTaskDeadlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTaskDeadlineResponse) ProtoMessage() {}

func (x *SetTaskDeadlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTaskDeadlineResponse.ProtoReflect.Descriptor instead.
func (*SetTaskDeadlineResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{18}
}

func (x *SetTaskDeadlineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetTaskDeadlineResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LectorId      int32                  `protobuf:"varint,1,opt,name=lector_id,json=lectorId,proto3" json:"lector_id,omitempty"`
	GroupId       int32                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Deadline      string                 `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	DisciplineId  int32                  `protobuf:"varint,6,opt,name=discipline_id,json=disciplineId,proto3" json:"discipline_id,omitempty"`
	ContentUrl    string                 `protobuf:"bytes,7,opt,name=content_url,json=contentUrl,proto3" json:"content_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkRequest) Reset() {
	*x = CreateWorkRequest{}
	mi := &file_proto_work_work_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkRequest) ProtoMessage() {}

func (x *CreateWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{19}
}

func (x *CreateWorkRequest) GetLectorId() int32 {
	if x != nil {
		return x.LectorId
	}
	return 0
}

func (x *CreateWorkRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateWorkRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateWorkRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateWorkRequest) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *CreateWorkRequest) GetDisciplineId() int32 {
	if x != nil {
		return x.DisciplineId
	}
	return 0
}

func (x *CreateWorkRequest) GetContentUrl() string {
	if x != nil {
		return x.ContentUrl
	}
	return ""
}

type CreateWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkResponse) Reset() {
	*x = CreateWorkResponse{}
	mi := &file_proto_work_work_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkResponse) ProtoMessage() {}

func (x *CreateWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{20}
}

func (x *CreateWorkResponse) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *CreateWorkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LoadTaskNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTaskNameRequest) Reset() {
	*x = LoadTaskNameRequest{}
	mi := &file_proto_work_work_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTaskNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTaskNameRequest) ProtoMessage() {}

func (x *LoadTaskNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTaskNameRequest.ProtoReflect.Descriptor instead.
func (*LoadTaskNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{21}
}

func (x *LoadTaskNameRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type LoadTaskNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTaskNameResponse) Reset() {
	*x = LoadTaskNameResponse{}
	mi := &file_proto_work_work_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTaskNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTaskNameResponse) ProtoMessage() {}

func (x *LoadTaskNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTaskNameResponse.ProtoReflect.Descriptor instead.
func (*LoadTaskNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{22}
}

func (x *LoadTaskNameResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LoadTaskNameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LoadTaskDescriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTaskDescriptionRequest) Reset() {
	*x = LoadTaskDescriptionRequest{}
	mi := &file_proto_work_work_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTaskDescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTaskDescriptionRequest) ProtoMessage() {}

func (x *LoadTaskDescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTaskDescriptionRequest.ProtoReflect.Descriptor instead.
func (*LoadTaskDescriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{23}
}

func (x *LoadTaskDescriptionRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type LoadTaskDescriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTaskDescriptionResponse) Reset() {
	*x = LoadTaskDescriptionResponse{}
	mi := &file_proto_work_work_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTaskDescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTaskDescriptionResponse) ProtoMessage() {}

func (x *LoadTaskDescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTaskDescriptionResponse.ProtoReflect.Descriptor instead.
func (*LoadTaskDescriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{24}
}

func (x *LoadTaskDescriptionResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LoadTaskDescriptionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LoadTaskDeadlineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTaskDeadlineRequest) Reset() {
	*x = LoadTaskDeadlineRequest{}
	mi := &file_proto_work_work_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTaskDeadlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTaskDeadlineRequest) ProtoMessage() {}

func (x *LoadTaskDeadlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTaskDeadlineRequest.ProtoReflect.Descriptor instead.
func (*LoadTaskDeadlineRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{25}
}

func (x *LoadTaskDeadlineRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type LoadTaskDeadlineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deadline      string                 `protobuf:"bytes,1,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTaskDeadlineResponse) Reset() {
	*x = LoadTaskDeadlineResponse{}
	mi := &file_proto_work_work_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTaskDeadlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTaskDeadlineResponse) ProtoMessage() {}

func (x *LoadTaskDeadlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTaskDeadlineResponse.ProtoReflect.Descriptor instead.
func (*LoadTaskDeadlineResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{26}
}

func (x *LoadTaskDeadlineResponse) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *LoadTaskDeadlineResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LectorId      int32                  `protobuf:"varint,1,opt,name=lector_id,json=lectorId,proto3" json:"lector_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsRequest) Reset() {
	*x = GetGroupsRequest{}
	mi := &file_proto_work_work_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsRequest) ProtoMessage() {}

func (x *GetGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsRequest.ProtoReflect.Descriptor instead.
func (*GetGroupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{27}
}

func (x *GetGroupsRequest) GetLectorId() int32 {
	if x != nil {
		return x.LectorId
	}
	return 0
}

type GetGroupsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Groups        []*GetGroupsResponse_Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	Error         string                     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsResponse) Reset() {
	*x = GetGroupsResponse{}
	mi := &file_proto_work_work_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsResponse) ProtoMessage() {}

func (x *GetGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsResponse.ProtoReflect.Descriptor instead.
func (*GetGroupsResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{28}
}

func (x *GetGroupsResponse) GetGroups() []*GetGroupsResponse_Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *GetGroupsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetDisciplinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LectorId      int32                  `protobuf:"varint,1,opt,name=lector_id,json=lectorId,proto3" json:"lector_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDisciplinesRequest) Reset() {
	*x = GetDisciplinesRequest{}
	mi := &file_proto_work_work_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDisciplinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisciplinesRequest) ProtoMessage() {}

func (x *GetDisciplinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDisciplinesRequest.ProtoReflect.Descriptor instead.
func (*GetDisciplinesRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{29}
}

func (x *GetDisciplinesRequest) GetLectorId() int32 {
	if x != nil {
		return x.LectorId
	}
	return 0
}

type GetDisciplinesResponse struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Disciplines   []*GetDisciplinesResponse_Discipline `protobuf:"bytes,1,rep,name=disciplines,proto3" json:"disciplines,omitempty"`
	Error         string                               `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDisciplinesResponse) Reset() {
	*x = GetDisciplinesResponse{}
	mi := &file_proto_work_work_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDisciplinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisciplinesResponse) ProtoMessage() {}

func (x *GetDisciplinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDisciplinesResponse.ProtoReflect.Descriptor instead.
func (*GetDisciplinesResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{30}
}

func (x *GetDisciplinesResponse) GetDisciplines() []*GetDisciplinesResponse_Discipline {
	if x != nil {
		return x.Disciplines
	}
	return nil
}

func (x *GetDisciplinesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetTasksForSeminaristResponse_Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Deadline      string                 `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksForSeminaristResponse_Task) Reset() {
	*x = GetTasksForSeminaristResponse_Task{}
	mi := &file_proto_work_work_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksForSeminaristResponse_Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksForSeminaristResponse_Task) ProtoMessage() {}

func (x *GetTasksForSeminaristResponse_Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksForSeminaristResponse_Task.ProtoReflect.Descriptor instead.
func (*GetTasksForSeminaristResponse_Task) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetTasksForSeminaristResponse_Task) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTasksForSeminaristResponse_Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetTasksForSeminaristResponse_Task) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

type GetStudentWorksForSeminaristResponse_StudentWork struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StudentName   string                 `protobuf:"bytes,4,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentWorksForSeminaristResponse_StudentWork) Reset() {
	*x = GetStudentWorksForSeminaristResponse_StudentWork{}
	mi := &file_proto_work_work_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentWorksForSeminaristResponse_StudentWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentWorksForSeminaristResponse_StudentWork) ProtoMessage() {}

func (x *GetStudentWorksForSeminaristResponse_StudentWork) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentWorksForSeminaristResponse_StudentWork.ProtoReflect.Descriptor instead.
func (*GetStudentWorksForSeminaristResponse_StudentWork) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetStudentWorksForSeminaristResponse_StudentWork) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetStudentWorksForSeminaristResponse_StudentWork) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetStudentWorksForSeminaristResponse_StudentWork) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetStudentWorksForSeminaristResponse_StudentWork) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

type GetGroupsResponse_Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsResponse_Group) Reset() {
	*x = GetGroupsResponse_Group{}
	mi := &file_proto_work_work_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsResponse_Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsResponse_Group) ProtoMessage() {}

func (x *GetGroupsResponse_Group) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsResponse_Group.ProtoReflect.Descriptor instead.
func (*GetGroupsResponse_Group) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{28, 0}
}

func (x *GetGroupsResponse_Group) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetGroupsResponse_Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDisciplinesResponse_Discipline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDisciplinesResponse_Discipline) Reset() {
	*x = GetDisciplinesResponse_Discipline{}
	mi := &file_proto_work_work_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDisciplinesResponse_Discipline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisciplinesResponse_Discipline) ProtoMessage() {}

func (x *GetDisciplinesResponse_Discipline) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDisciplinesResponse_Discipline.ProtoReflect.Descriptor instead.
func (*GetDisciplinesResponse_Discipline) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{30, 0}
}

func (x *GetDisciplinesResponse_Discipline) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetDisciplinesResponse_Discipline) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_work_work_proto protoreflect.FileDescriptor

const file_proto_work_work_proto_rawDesc = "" +
	"\n" +
	"\x15proto/work/work.proto\x12\x04work\"C\n" +
	"\x1cGetTasksForSeminaristRequest\x12#\n" +
	"\rseminarist_id\x18\x01 \x01(\tR\fseminaristId\"\xbf\x01\n" +
	"\x1dGetTasksForSeminaristResponse\x12>\n" +
	"\x05tasks\x18\x01 \x03(\v2(.work.GetTasksForSeminaristResponse.TaskR\x05tasks\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x1aH\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bdeadline\x18\x03 \x01(\tR\bdeadline\"J\n" +
	"#GetStudentWorksForSeminaristRequest\x12#\n" +
	"\rseminarist_id\x18\x01 \x01(\tR\fseminaristId\"\x81\x02\n" +
	"$GetStudentWorksForSeminaristResponse\x12L\n" +
	"\x05works\x18\x01 \x03(\v26.work.GetStudentWorksForSeminaristResponse.StudentWorkR\x05works\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x1au\n" +
	"\vStudentWork\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12!\n" +
	"\fstudent_name\x18\x04 \x01(\tR\vstudentName\"0\n" +
	"\x15GetTaskDetailsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\"\xca\x01\n" +
	"\x16GetTaskDetailsResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bdeadline\x18\x03 \x01(\tR\bdeadline\x12\x1d\n" +
	"\n" +
	"group_name\x18\x04 \x01(\tR\tgroupName\x12'\n" +
	"\x0fdiscipline_name\x18\x05 \x01(\tR\x0edisciplineName\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"~\n" +
	"#UpdateTaskGroupAndDisciplineRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x05R\agroupId\x12#\n" +
	"\rdiscipline_id\x18\x03 \x01(\x05R\fdisciplineId\"V\n" +
	"$UpdateTaskGroupAndDisciplineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"7\n" +
	"\x18GetTasksForLectorRequest\x12\x1b\n" +
	"\tlector_id\x18\x01 \x01(\x05R\blectorId\"H\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bdeadline\x18\x03 \x01(\tR\bdeadline\"S\n" +
	"\x19GetTasksForLectorResponse\x12 \n" +
	"\x05tasks\x18\x01 \x03(\v2\n" +
	".work.TaskR\x05tasks\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\",\n" +
	"\x11DeleteTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\"D\n" +
	"\x12DeleteTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"D\n" +
	"\x13SetTaskTitleRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"F\n" +
	"\x14SetTaskTitleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"V\n" +
	"\x19SetTaskDescriptionRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"L\n" +
	"\x1aSetTaskDescriptionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"M\n" +
	"\x16SetTaskDeadlineRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12\x1a\n" +
	"\bdeadline\x18\x02 \x01(\tR\bdeadline\"I\n" +
	"\x17SetTaskDeadlineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xe5\x01\n" +
	"\x11CreateWorkRequest\x12\x1b\n" +
	"\tlector_id\x18\x01 \x01(\x05R\blectorId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x05R\agroupId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bdeadline\x18\x05 \x01(\tR\bdeadline\x12#\n" +
	"\rdiscipline_id\x18\x06 \x01(\x05R\fdisciplineId\x12\x1f\n" +
	"\vcontent_url\x18\a \x01(\tR\n" +
	"contentUrl\"C\n" +
	"\x12CreateWorkResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\".\n" +
	"\x13LoadTaskNameRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\"B\n" +
	"\x14LoadTaskNameResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"5\n" +
	"\x1aLoadTaskDescriptionRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\"U\n" +
	"\x1bLoadTaskDescriptionResponse\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"2\n" +
	"\x17LoadTaskDeadlineRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\"L\n" +
	"\x18LoadTaskDeadlineResponse\x12\x1a\n" +
	"\bdeadline\x18\x01 \x01(\tR\bdeadline\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"/\n" +
	"\x10GetGroupsRequest\x12\x1b\n" +
	"\tlector_id\x18\x01 \x01(\x05R\blectorId\"\x8d\x01\n" +
	"\x11GetGroupsResponse\x125\n" +
	"\x06groups\x18\x01 \x03(\v2\x1d.work.GetGroupsResponse.GroupR\x06groups\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x1a+\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"4\n" +
	"\x15GetDisciplinesRequest\x12\x1b\n" +
	"\tlector_id\x18\x01 \x01(\x05R\blectorId\"\xab\x01\n" +
	"\x16GetDisciplinesResponse\x12I\n" +
	"\vdisciplines\x18\x01 \x03(\v2'.work.GetDisciplinesResponse.DisciplineR\vdisciplines\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x1a0\n" +
	"\n" +
	"Discipline\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\x8d\n" +
	"\n" +
	"\vWorkService\x12V\n" +
	"\x11GetTasksForLector\x12\x1e.work.GetTasksForLectorRequest\x1a\x1f.work.GetTasksForLectorResponse\"\x00\x12A\n" +
	"\n" +
	"DeleteTask\x12\x17.work.DeleteTaskRequest\x1a\x18.work.DeleteTaskResponse\"\x00\x12G\n" +
	"\fSetTaskTitle\x12\x19.work.SetTaskTitleRequest\x1a\x1a.work.SetTaskTitleResponse\"\x00\x12Y\n" +
	"\x12SetTaskDescription\x12\x1f.work.SetTaskDescriptionRequest\x1a .work.SetTaskDescriptionResponse\"\x00\x12P\n" +
	"\x0fSetTaskDeadline\x12\x1c.work.SetTaskDeadlineRequest\x1a\x1d.work.SetTaskDeadlineResponse\"\x00\x12A\n" +
	"\n" +
	"CreateWork\x12\x17.work.CreateWorkRequest\x1a\x18.work.CreateWorkResponse\"\x00\x12G\n" +
	"\fLoadTaskName\x12\x19.work.LoadTaskNameRequest\x1a\x1a.work.LoadTaskNameResponse\"\x00\x12\\\n" +
	"\x13LoadTaskDescription\x12 .work.LoadTaskDescriptionRequest\x1a!.work.LoadTaskDescriptionResponse\"\x00\x12S\n" +
	"\x10LoadTaskDeadline\x12\x1d.work.LoadTaskDeadlineRequest\x1a\x1e.work.LoadTaskDeadlineResponse\"\x00\x12<\n" +
	"\tGetGroups\x12\x16.work.GetGroupsRequest\x1a\x17.work.GetGroupsResponse\x12K\n" +
	"\x0eGetDisciplines\x12\x1b.work.GetDisciplinesRequest\x1a\x1c.work.GetDisciplinesResponse\x12M\n" +
	"\x0eGetTaskDetails\x12\x1b.work.GetTaskDetailsRequest\x1a\x1c.work.GetTaskDetailsResponse\"\x00\x12w\n" +
	"\x1cUpdateTaskGroupAndDiscipline\x12).work.UpdateTaskGroupAndDisciplineRequest\x1a*.work.UpdateTaskGroupAndDisciplineResponse\"\x00\x12w\n" +
	"\x1cGetStudentWorksForSeminarist\x12).work.GetStudentWorksForSeminaristRequest\x1a*.work.GetStudentWorksForSeminaristResponse\"\x00\x12b\n" +
	"\x15GetTasksForSeminarist\x12\".work.GetTasksForSeminaristRequest\x1a#.work.GetTasksForSeminaristResponse\"\x00B\x13Z\x11./proto/work;workb\x06proto3"

var (
	file_proto_work_work_proto_rawDescOnce sync.Once
	file_proto_work_work_proto_rawDescData []byte
)

func file_proto_work_work_proto_rawDescGZIP() []byte {
	file_proto_work_work_proto_rawDescOnce.Do(func() {
		file_proto_work_work_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_work_work_proto_rawDesc), len(file_proto_work_work_proto_rawDesc)))
	})
	return file_proto_work_work_proto_rawDescData
}

var file_proto_work_work_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_proto_work_work_proto_goTypes = []any{
	(*GetTasksForSeminaristRequest)(nil),                     // 0: work.GetTasksForSeminaristRequest
	(*GetTasksForSeminaristResponse)(nil),                    // 1: work.GetTasksForSeminaristResponse
	(*GetStudentWorksForSeminaristRequest)(nil),              // 2: work.GetStudentWorksForSeminaristRequest
	(*GetStudentWorksForSeminaristResponse)(nil),             // 3: work.GetStudentWorksForSeminaristResponse
	(*GetTaskDetailsRequest)(nil),                            // 4: work.GetTaskDetailsRequest
	(*GetTaskDetailsResponse)(nil),                           // 5: work.GetTaskDetailsResponse
	(*UpdateTaskGroupAndDisciplineRequest)(nil),              // 6: work.UpdateTaskGroupAndDisciplineRequest
	(*UpdateTaskGroupAndDisciplineResponse)(nil),             // 7: work.UpdateTaskGroupAndDisciplineResponse
	(*GetTasksForLectorRequest)(nil),                         // 8: work.GetTasksForLectorRequest
	(*Task)(nil),                                             // 9: work.Task
	(*GetTasksForLectorResponse)(nil),                        // 10: work.GetTasksForLectorResponse
	(*DeleteTaskRequest)(nil),                                // 11: work.DeleteTaskRequest
	(*DeleteTaskResponse)(nil),                               // 12: work.DeleteTaskResponse
	(*SetTaskTitleRequest)(nil),                              // 13: work.SetTaskTitleRequest
	(*SetTaskTitleResponse)(nil),                             // 14: work.SetTaskTitleResponse
	(*SetTaskDescriptionRequest)(nil),                        // 15: work.SetTaskDescriptionRequest
	(*SetTaskDescriptionResponse)(nil),                       // 16: work.SetTaskDescriptionResponse
	(*SetTaskDeadlineRequest)(nil),                           // 17: work.SetTaskDeadlineRequest
	(*SetTaskDeadlineResponse)(nil),                          // 18: work.SetTaskDeadlineResponse
	(*CreateWorkRequest)(nil),                                // 19: work.CreateWorkRequest
	(*CreateWorkResponse)(nil),                               // 20: work.CreateWorkResponse
	(*LoadTaskNameRequest)(nil),                              // 21: work.LoadTaskNameRequest
	(*LoadTaskNameResponse)(nil),                             // 22: work.LoadTaskNameResponse
	(*LoadTaskDescriptionRequest)(nil),                       // 23: work.LoadTaskDescriptionRequest
	(*LoadTaskDescriptionResponse)(nil),                      // 24: work.LoadTaskDescriptionResponse
	(*LoadTaskDeadlineRequest)(nil),                          // 25: work.LoadTaskDeadlineRequest
	(*LoadTaskDeadlineResponse)(nil),                         // 26: work.LoadTaskDeadlineResponse
	(*GetGroupsRequest)(nil),                                 // 27: work.GetGroupsRequest
	(*GetGroupsResponse)(nil),                                // 28: work.GetGroupsResponse
	(*GetDisciplinesRequest)(nil),                            // 29: work.GetDisciplinesRequest
	(*GetDisciplinesResponse)(nil),                           // 30: work.GetDisciplinesResponse
	(*GetTasksForSeminaristResponse_Task)(nil),               // 31: work.GetTasksForSeminaristResponse.Task
	(*GetStudentWorksForSeminaristResponse_StudentWork)(nil), // 32: work.GetStudentWorksForSeminaristResponse.StudentWork
	(*GetGroupsResponse_Group)(nil),                          // 33: work.GetGroupsResponse.Group
	(*GetDisciplinesResponse_Discipline)(nil),                // 34: work.GetDisciplinesResponse.Discipline
}
var file_proto_work_work_proto_depIdxs = []int32{
	31, // 0: work.GetTasksForSeminaristResponse.tasks:type_name -> work.GetTasksForSeminaristResponse.Task
	32, // 1: work.GetStudentWorksForSeminaristResponse.works:type_name -> work.GetStudentWorksForSeminaristResponse.StudentWork
	9,  // 2: work.GetTasksForLectorResponse.tasks:type_name -> work.Task
	33, // 3: work.GetGroupsResponse.groups:type_name -> work.GetGroupsResponse.Group
	34, // 4: work.GetDisciplinesResponse.disciplines:type_name -> work.GetDisciplinesResponse.Discipline
	8,  // 5: work.WorkService.GetTasksForLector:input_type -> work.GetTasksForLectorRequest
	11, // 6: work.WorkService.DeleteTask:input_type -> work.DeleteTaskRequest
	13, // 7: work.WorkService.SetTaskTitle:input_type -> work.SetTaskTitleRequest
	15, // 8: work.WorkService.SetTaskDescription:input_type -> work.SetTaskDescriptionRequest
	17, // 9: work.WorkService.SetTaskDeadline:input_type -> work.SetTaskDeadlineRequest
	19, // 10: work.WorkService.CreateWork:input_type -> work.CreateWorkRequest
	21, // 11: work.WorkService.LoadTaskName:input_type -> work.LoadTaskNameRequest
	23, // 12: work.WorkService.LoadTaskDescription:input_type -> work.LoadTaskDescriptionRequest
	25, // 13: work.WorkService.LoadTaskDeadline:input_type -> work.LoadTaskDeadlineRequest
	27, // 14: work.WorkService.GetGroups:input_type -> work.GetGroupsRequest
	29, // 15: work.WorkService.GetDisciplines:input_type -> work.GetDisciplinesRequest
	4,  // 16: work.WorkService.GetTaskDetails:input_type -> work.GetTaskDetailsRequest
	6,  // 17: work.WorkService.UpdateTaskGroupAndDiscipline:input_type -> work.UpdateTaskGroupAndDisciplineRequest
	2,  // 18: work.WorkService.GetStudentWorksForSeminarist:input_type -> work.GetStudentWorksForSeminaristRequest
	0,  // 19: work.WorkService.GetTasksForSeminarist:input_type -> work.GetTasksForSeminaristRequest
	10, // 20: work.WorkService.GetTasksForLector:output_type -> work.GetTasksForLectorResponse
	12, // 21: work.WorkService.DeleteTask:output_type -> work.DeleteTaskResponse
	14, // 22: work.WorkService.SetTaskTitle:output_type -> work.SetTaskTitleResponse
	16, // 23: work.WorkService.SetTaskDescription:output_type -> work.SetTaskDescriptionResponse
	18, // 24: work.WorkService.SetTaskDeadline:output_type -> work.SetTaskDeadlineResponse
	20, // 25: work.WorkService.CreateWork:output_type -> work.CreateWorkResponse
	22, // 26: work.WorkService.LoadTaskName:output_type -> work.LoadTaskNameResponse
	24, // 27: work.WorkService.LoadTaskDescription:output_type -> work.LoadTaskDescriptionResponse
	26, // 28: work.WorkService.LoadTaskDeadline:output_type -> work.LoadTaskDeadlineResponse
	28, // 29: work.WorkService.GetGroups:output_type -> work.GetGroupsResponse
	30, // 30: work.WorkService.GetDisciplines:output_type -> work.GetDisciplinesResponse
	5,  // 31: work.WorkService.GetTaskDetails:output_type -> work.GetTaskDetailsResponse
	7,  // 32: work.WorkService.UpdateTaskGroupAndDiscipline:output_type -> work.UpdateTaskGroupAndDisciplineResponse
	3,  // 33: work.WorkService.GetStudentWorksForSeminarist:output_type -> work.GetStudentWorksForSeminaristResponse
	1,  // 34: work.WorkService.GetTasksForSeminarist:output_type -> work.GetTasksForSeminaristResponse
	20, // [20:35] is the sub-list for method output_type
	5,  // [5:20] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_work_work_proto_init() }
func file_proto_work_work_proto_init() {
	if File_proto_work_work_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_work_work_proto_rawDesc), len(file_proto_work_work_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_work_work_proto_goTypes,
		DependencyIndexes: file_proto_work_work_proto_depIdxs,
		MessageInfos:      file_proto_work_work_proto_msgTypes,
	}.Build()
	File_proto_work_work_proto = out.File
	file_proto_work_work_proto_goTypes = nil
	file_proto_work_work_proto_depIdxs = nil
}
