// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/work/work.proto

package work

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        int32                  `protobuf:"varint,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	AssistantId   int32                  `protobuf:"varint,3,opt,name=assistant_id,json=assistantId,proto3" json:"assistant_id,omitempty"` // 0 для очистки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkRequest) Reset() {
	*x = UpdateWorkRequest{}
	mi := &file_proto_work_work_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkRequest) ProtoMessage() {}

func (x *UpdateWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateWorkRequest) GetWorkId() int32 {
	if x != nil {
		return x.WorkId
	}
	return 0
}

func (x *UpdateWorkRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateWorkRequest) GetAssistantId() int32 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

type UpdateWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkResponse) Reset() {
	*x = UpdateWorkResponse{}
	mi := &file_proto_work_work_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkResponse) ProtoMessage() {}

func (x *UpdateWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkResponse.ProtoReflect.Descriptor instead.
func (*UpdateWorkResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateWorkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetStudentWorksByTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentWorksByTaskRequest) Reset() {
	*x = GetStudentWorksByTaskRequest{}
	mi := &file_proto_work_work_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentWorksByTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentWorksByTaskRequest) ProtoMessage() {}

func (x *GetStudentWorksByTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentWorksByTaskRequest.ProtoReflect.Descriptor instead.
func (*GetStudentWorksByTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{2}
}

func (x *GetStudentWorksByTaskRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type GetStudentWorksByTaskResponse struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Works         []*GetStudentWorksByTaskResponse_StudentWork `protobuf:"bytes,1,rep,name=works,proto3" json:"works,omitempty"`
	Error         string                                       `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentWorksByTaskResponse) Reset() {
	*x = GetStudentWorksByTaskResponse{}
	mi := &file_proto_work_work_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentWorksByTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentWorksByTaskResponse) ProtoMessage() {}

func (x *GetStudentWorksByTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentWorksByTaskResponse.ProtoReflect.Descriptor instead.
func (*GetStudentWorksByTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{3}
}

func (x *GetStudentWorksByTaskResponse) GetWorks() []*GetStudentWorksByTaskResponse_StudentWork {
	if x != nil {
		return x.Works
	}
	return nil
}

func (x *GetStudentWorksByTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetAssistantsByDisciplineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisciplineId  int32                  `protobuf:"varint,1,opt,name=discipline_id,json=disciplineId,proto3" json:"discipline_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssistantsByDisciplineRequest) Reset() {
	*x = GetAssistantsByDisciplineRequest{}
	mi := &file_proto_work_work_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssistantsByDisciplineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssistantsByDisciplineRequest) ProtoMessage() {}

func (x *GetAssistantsByDisciplineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssistantsByDisciplineRequest.ProtoReflect.Descriptor instead.
func (*GetAssistantsByDisciplineRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{4}
}

func (x *GetAssistantsByDisciplineRequest) GetDisciplineId() int32 {
	if x != nil {
		return x.DisciplineId
	}
	return 0
}

type GetAssistantsByDisciplineResponse struct {
	state         protoimpl.MessageState                         `protogen:"open.v1"`
	Assistants    []*GetAssistantsByDisciplineResponse_Assistant `protobuf:"bytes,1,rep,name=assistants,proto3" json:"assistants,omitempty"`
	Error         string                                         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssistantsByDisciplineResponse) Reset() {
	*x = GetAssistantsByDisciplineResponse{}
	mi := &file_proto_work_work_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssistantsByDisciplineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssistantsByDisciplineResponse) ProtoMessage() {}

func (x *GetAssistantsByDisciplineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssistantsByDisciplineResponse.ProtoReflect.Descriptor instead.
func (*GetAssistantsByDisciplineResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{5}
}

func (x *GetAssistantsByDisciplineResponse) GetAssistants() []*GetAssistantsByDisciplineResponse_Assistant {
	if x != nil {
		return x.Assistants
	}
	return nil
}

func (x *GetAssistantsByDisciplineResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AssignAssistantsToWorksRequest struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Assignments   []*AssignAssistantsToWorksRequest_Assignment `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignAssistantsToWorksRequest) Reset() {
	*x = AssignAssistantsToWorksRequest{}
	mi := &file_proto_work_work_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignAssistantsToWorksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAssistantsToWorksRequest) ProtoMessage() {}

func (x *AssignAssistantsToWorksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAssistantsToWorksRequest.ProtoReflect.Descriptor instead.
func (*AssignAssistantsToWorksRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{6}
}

func (x *AssignAssistantsToWorksRequest) GetAssignments() []*AssignAssistantsToWorksRequest_Assignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type AssignAssistantsToWorksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignAssistantsToWorksResponse) Reset() {
	*x = AssignAssistantsToWorksResponse{}
	mi := &file_proto_work_work_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignAssistantsToWorksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAssistantsToWorksResponse) ProtoMessage() {}

func (x *AssignAssistantsToWorksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAssistantsToWorksResponse.ProtoReflect.Descriptor instead.
func (*AssignAssistantsToWorksResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{7}
}

func (x *AssignAssistantsToWorksResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AssignAssistantsToWorksResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetTasksForSeminaristRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeminaristId  string                 `protobuf:"bytes,1,opt,name=seminarist_id,json=seminaristId,proto3" json:"seminarist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksForSeminaristRequest) Reset() {
	*x = GetTasksForSeminaristRequest{}
	mi := &file_proto_work_work_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksForSeminaristRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksForSeminaristRequest) ProtoMessage() {}

func (x *GetTasksForSeminaristRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksForSeminaristRequest.ProtoReflect.Descriptor instead.
func (*GetTasksForSeminaristRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{8}
}

func (x *GetTasksForSeminaristRequest) GetSeminaristId() string {
	if x != nil {
		return x.SeminaristId
	}
	return ""
}

type GetTasksForSeminaristResponse struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Tasks         []*GetTasksForSeminaristResponse_Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Error         string                                `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksForSeminaristResponse) Reset() {
	*x = GetTasksForSeminaristResponse{}
	mi := &file_proto_work_work_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksForSeminaristResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksForSeminaristResponse) ProtoMessage() {}

func (x *GetTasksForSeminaristResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksForSeminaristResponse.ProtoReflect.Descriptor instead.
func (*GetTasksForSeminaristResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{9}
}

func (x *GetTasksForSeminaristResponse) GetTasks() []*GetTasksForSeminaristResponse_Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *GetTasksForSeminaristResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetStudentWorksForSeminaristRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeminaristId  string                 `protobuf:"bytes,1,opt,name=seminarist_id,json=seminaristId,proto3" json:"seminarist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentWorksForSeminaristRequest) Reset() {
	*x = GetStudentWorksForSeminaristRequest{}
	mi := &file_proto_work_work_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentWorksForSeminaristRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentWorksForSeminaristRequest) ProtoMessage() {}

func (x *GetStudentWorksForSeminaristRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentWorksForSeminaristRequest.ProtoReflect.Descriptor instead.
func (*GetStudentWorksForSeminaristRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{10}
}

func (x *GetStudentWorksForSeminaristRequest) GetSeminaristId() string {
	if x != nil {
		return x.SeminaristId
	}
	return ""
}

type GetStudentWorksForSeminaristResponse struct {
	state         protoimpl.MessageState                              `protogen:"open.v1"`
	Works         []*GetStudentWorksForSeminaristResponse_StudentWork `protobuf:"bytes,1,rep,name=works,proto3" json:"works,omitempty"`
	Error         string                                              `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentWorksForSeminaristResponse) Reset() {
	*x = GetStudentWorksForSeminaristResponse{}
	mi := &file_proto_work_work_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentWorksForSeminaristResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentWorksForSeminaristResponse) ProtoMessage() {}

func (x *GetStudentWorksForSeminaristResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentWorksForSeminaristResponse.ProtoReflect.Descriptor instead.
func (*GetStudentWorksForSeminaristResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{11}
}

func (x *GetStudentWorksForSeminaristResponse) GetWorks() []*GetStudentWorksForSeminaristResponse_StudentWork {
	if x != nil {
		return x.Works
	}
	return nil
}

func (x *GetStudentWorksForSeminaristResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetTaskDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskDetailsRequest) Reset() {
	*x = GetTaskDetailsRequest{}
	mi := &file_proto_work_work_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskDetailsRequest) ProtoMessage() {}

func (x *GetTaskDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetTaskDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{12}
}

func (x *GetTaskDetailsRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type GetTaskDetailsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Title            string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Deadline         string                 `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	GroupName        string                 `protobuf:"bytes,4,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	DisciplineName   string                 `protobuf:"bytes,5,opt,name=discipline_name,json=disciplineName,proto3" json:"discipline_name,omitempty"`
	LectorName       string                 `protobuf:"bytes,6,opt,name=lector_name,json=lectorName,proto3" json:"lector_name,omitempty"`
	LectorSurname    string                 `protobuf:"bytes,7,opt,name=lector_surname,json=lectorSurname,proto3" json:"lector_surname,omitempty"`
	LectorPatronymic string                 `protobuf:"bytes,8,opt,name=lector_patronymic,json=lectorPatronymic,proto3" json:"lector_patronymic,omitempty"`
	DisciplineId     int32                  `protobuf:"varint,9,opt,name=discipline_id,json=disciplineId,proto3" json:"discipline_id,omitempty"`
	Error            string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetTaskDetailsResponse) Reset() {
	*x = GetTaskDetailsResponse{}
	mi := &file_proto_work_work_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskDetailsResponse) ProtoMessage() {}

func (x *GetTaskDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetTaskDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{13}
}

func (x *GetTaskDetailsResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetTaskDetailsResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetTaskDetailsResponse) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *GetTaskDetailsResponse) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GetTaskDetailsResponse) GetDisciplineName() string {
	if x != nil {
		return x.DisciplineName
	}
	return ""
}

func (x *GetTaskDetailsResponse) GetLectorName() string {
	if x != nil {
		return x.LectorName
	}
	return ""
}

func (x *GetTaskDetailsResponse) GetLectorSurname() string {
	if x != nil {
		return x.LectorSurname
	}
	return ""
}

func (x *GetTaskDetailsResponse) GetLectorPatronymic() string {
	if x != nil {
		return x.LectorPatronymic
	}
	return ""
}

func (x *GetTaskDetailsResponse) GetDisciplineId() int32 {
	if x != nil {
		return x.DisciplineId
	}
	return 0
}

func (x *GetTaskDetailsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateTaskGroupAndDisciplineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	GroupId       int32                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	DisciplineId  int32                  `protobuf:"varint,3,opt,name=discipline_id,json=disciplineId,proto3" json:"discipline_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskGroupAndDisciplineRequest) Reset() {
	*x = UpdateTaskGroupAndDisciplineRequest{}
	mi := &file_proto_work_work_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskGroupAndDisciplineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskGroupAndDisciplineRequest) ProtoMessage() {}

func (x *UpdateTaskGroupAndDisciplineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskGroupAndDisciplineRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskGroupAndDisciplineRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateTaskGroupAndDisciplineRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *UpdateTaskGroupAndDisciplineRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UpdateTaskGroupAndDisciplineRequest) GetDisciplineId() int32 {
	if x != nil {
		return x.DisciplineId
	}
	return 0
}

type UpdateTaskGroupAndDisciplineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskGroupAndDisciplineResponse) Reset() {
	*x = UpdateTaskGroupAndDisciplineResponse{}
	mi := &file_proto_work_work_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskGroupAndDisciplineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskGroupAndDisciplineResponse) ProtoMessage() {}

func (x *UpdateTaskGroupAndDisciplineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskGroupAndDisciplineResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskGroupAndDisciplineResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateTaskGroupAndDisciplineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateTaskGroupAndDisciplineResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetTasksForLectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LectorId      int32                  `protobuf:"varint,1,opt,name=lector_id,json=lectorId,proto3" json:"lector_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksForLectorRequest) Reset() {
	*x = GetTasksForLectorRequest{}
	mi := &file_proto_work_work_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksForLectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksForLectorRequest) ProtoMessage() {}

func (x *GetTasksForLectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksForLectorRequest.ProtoReflect.Descriptor instead.
func (*GetTasksForLectorRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{16}
}

func (x *GetTasksForLectorRequest) GetLectorId() int32 {
	if x != nil {
		return x.LectorId
	}
	return 0
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Deadline      string                 `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_work_work_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{17}
}

func (x *Task) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

type GetTasksForLectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksForLectorResponse) Reset() {
	*x = GetTasksForLectorResponse{}
	mi := &file_proto_work_work_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksForLectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksForLectorResponse) ProtoMessage() {}

func (x *GetTasksForLectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksForLectorResponse.ProtoReflect.Descriptor instead.
func (*GetTasksForLectorResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{18}
}

func (x *GetTasksForLectorResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *GetTasksForLectorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_proto_work_work_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteTaskRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_proto_work_work_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetTaskTitleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTaskTitleRequest) Reset() {
	*x = SetTaskTitleRequest{}
	mi := &file_proto_work_work_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTaskTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTaskTitleRequest) ProtoMessage() {}

func (x *SetTaskTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTaskTitleRequest.ProtoReflect.Descriptor instead.
func (*SetTaskTitleRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{21}
}

func (x *SetTaskTitleRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *SetTaskTitleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type SetTaskTitleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTaskTitleResponse) Reset() {
	*x = SetTaskTitleResponse{}
	mi := &file_proto_work_work_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTaskTitleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTaskTitleResponse) ProtoMessage() {}

func (x *SetTaskTitleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTaskTitleResponse.ProtoReflect.Descriptor instead.
func (*SetTaskTitleResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{22}
}

func (x *SetTaskTitleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetTaskTitleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetTaskDescriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTaskDescriptionRequest) Reset() {
	*x = SetTaskDescriptionRequest{}
	mi := &file_proto_work_work_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTaskDescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTaskDescriptionRequest) ProtoMessage() {}

func (x *SetTaskDescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTaskDescriptionRequest.ProtoReflect.Descriptor instead.
func (*SetTaskDescriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{23}
}

func (x *SetTaskDescriptionRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *SetTaskDescriptionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SetTaskDescriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTaskDescriptionResponse) Reset() {
	*x = SetTaskDescriptionResponse{}
	mi := &file_proto_work_work_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTaskDescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTaskDescriptionResponse) ProtoMessage() {}

func (x *SetTaskDescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTaskDescriptionResponse.ProtoReflect.Descriptor instead.
func (*SetTaskDescriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{24}
}

func (x *SetTaskDescriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetTaskDescriptionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetTaskDeadlineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Deadline      string                 `protobuf:"bytes,2,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTaskDeadlineRequest) Reset() {
	*x = SetTaskDeadlineRequest{}
	mi := &file_proto_work_work_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTaskDeadlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTaskDeadlineRequest) ProtoMessage() {}

func (x *SetTaskDeadlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTaskDeadlineRequest.ProtoReflect.Descriptor instead.
func (*SetTaskDeadlineRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{25}
}

func (x *SetTaskDeadlineRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *SetTaskDeadlineRequest) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

type SetTaskDeadlineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTaskDeadlineResponse) Reset() {
	*x = SetTaskDeadlineResponse{}
	mi := &file_proto_work_work_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTaskDeadlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTaskDeadlineResponse) ProtoMessage() {}

func (x *SetTaskDeadlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTaskDeadlineResponse.ProtoReflect.Descriptor instead.
func (*SetTaskDeadlineResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{26}
}

func (x *SetTaskDeadlineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetTaskDeadlineResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LectorId      int32                  `protobuf:"varint,1,opt,name=lector_id,json=lectorId,proto3" json:"lector_id,omitempty"`
	GroupId       int32                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Deadline      string                 `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	DisciplineId  int32                  `protobuf:"varint,6,opt,name=discipline_id,json=disciplineId,proto3" json:"discipline_id,omitempty"`
	ContentUrl    string                 `protobuf:"bytes,7,opt,name=content_url,json=contentUrl,proto3" json:"content_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkRequest) Reset() {
	*x = CreateWorkRequest{}
	mi := &file_proto_work_work_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkRequest) ProtoMessage() {}

func (x *CreateWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{27}
}

func (x *CreateWorkRequest) GetLectorId() int32 {
	if x != nil {
		return x.LectorId
	}
	return 0
}

func (x *CreateWorkRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateWorkRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateWorkRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateWorkRequest) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *CreateWorkRequest) GetDisciplineId() int32 {
	if x != nil {
		return x.DisciplineId
	}
	return 0
}

func (x *CreateWorkRequest) GetContentUrl() string {
	if x != nil {
		return x.ContentUrl
	}
	return ""
}

type CreateWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkResponse) Reset() {
	*x = CreateWorkResponse{}
	mi := &file_proto_work_work_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkResponse) ProtoMessage() {}

func (x *CreateWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{28}
}

func (x *CreateWorkResponse) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *CreateWorkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LoadTaskNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTaskNameRequest) Reset() {
	*x = LoadTaskNameRequest{}
	mi := &file_proto_work_work_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTaskNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTaskNameRequest) ProtoMessage() {}

func (x *LoadTaskNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTaskNameRequest.ProtoReflect.Descriptor instead.
func (*LoadTaskNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{29}
}

func (x *LoadTaskNameRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type LoadTaskNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTaskNameResponse) Reset() {
	*x = LoadTaskNameResponse{}
	mi := &file_proto_work_work_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTaskNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTaskNameResponse) ProtoMessage() {}

func (x *LoadTaskNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTaskNameResponse.ProtoReflect.Descriptor instead.
func (*LoadTaskNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{30}
}

func (x *LoadTaskNameResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LoadTaskNameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LoadTaskDescriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTaskDescriptionRequest) Reset() {
	*x = LoadTaskDescriptionRequest{}
	mi := &file_proto_work_work_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTaskDescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTaskDescriptionRequest) ProtoMessage() {}

func (x *LoadTaskDescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTaskDescriptionRequest.ProtoReflect.Descriptor instead.
func (*LoadTaskDescriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{31}
}

func (x *LoadTaskDescriptionRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type LoadTaskDescriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTaskDescriptionResponse) Reset() {
	*x = LoadTaskDescriptionResponse{}
	mi := &file_proto_work_work_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTaskDescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTaskDescriptionResponse) ProtoMessage() {}

func (x *LoadTaskDescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTaskDescriptionResponse.ProtoReflect.Descriptor instead.
func (*LoadTaskDescriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{32}
}

func (x *LoadTaskDescriptionResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LoadTaskDescriptionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LoadTaskDeadlineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTaskDeadlineRequest) Reset() {
	*x = LoadTaskDeadlineRequest{}
	mi := &file_proto_work_work_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTaskDeadlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTaskDeadlineRequest) ProtoMessage() {}

func (x *LoadTaskDeadlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTaskDeadlineRequest.ProtoReflect.Descriptor instead.
func (*LoadTaskDeadlineRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{33}
}

func (x *LoadTaskDeadlineRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type LoadTaskDeadlineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deadline      string                 `protobuf:"bytes,1,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTaskDeadlineResponse) Reset() {
	*x = LoadTaskDeadlineResponse{}
	mi := &file_proto_work_work_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTaskDeadlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTaskDeadlineResponse) ProtoMessage() {}

func (x *LoadTaskDeadlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTaskDeadlineResponse.ProtoReflect.Descriptor instead.
func (*LoadTaskDeadlineResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{34}
}

func (x *LoadTaskDeadlineResponse) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *LoadTaskDeadlineResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LectorId      int32                  `protobuf:"varint,1,opt,name=lector_id,json=lectorId,proto3" json:"lector_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsRequest) Reset() {
	*x = GetGroupsRequest{}
	mi := &file_proto_work_work_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsRequest) ProtoMessage() {}

func (x *GetGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsRequest.ProtoReflect.Descriptor instead.
func (*GetGroupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{35}
}

func (x *GetGroupsRequest) GetLectorId() int32 {
	if x != nil {
		return x.LectorId
	}
	return 0
}

type GetGroupsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Groups        []*GetGroupsResponse_Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	Error         string                     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsResponse) Reset() {
	*x = GetGroupsResponse{}
	mi := &file_proto_work_work_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsResponse) ProtoMessage() {}

func (x *GetGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsResponse.ProtoReflect.Descriptor instead.
func (*GetGroupsResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{36}
}

func (x *GetGroupsResponse) GetGroups() []*GetGroupsResponse_Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *GetGroupsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetDisciplinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LectorId      int32                  `protobuf:"varint,1,opt,name=lector_id,json=lectorId,proto3" json:"lector_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDisciplinesRequest) Reset() {
	*x = GetDisciplinesRequest{}
	mi := &file_proto_work_work_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDisciplinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisciplinesRequest) ProtoMessage() {}

func (x *GetDisciplinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDisciplinesRequest.ProtoReflect.Descriptor instead.
func (*GetDisciplinesRequest) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{37}
}

func (x *GetDisciplinesRequest) GetLectorId() int32 {
	if x != nil {
		return x.LectorId
	}
	return 0
}

type GetDisciplinesResponse struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Disciplines   []*GetDisciplinesResponse_Discipline `protobuf:"bytes,1,rep,name=disciplines,proto3" json:"disciplines,omitempty"`
	Error         string                               `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDisciplinesResponse) Reset() {
	*x = GetDisciplinesResponse{}
	mi := &file_proto_work_work_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDisciplinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisciplinesResponse) ProtoMessage() {}

func (x *GetDisciplinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDisciplinesResponse.ProtoReflect.Descriptor instead.
func (*GetDisciplinesResponse) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{38}
}

func (x *GetDisciplinesResponse) GetDisciplines() []*GetDisciplinesResponse_Discipline {
	if x != nil {
		return x.Disciplines
	}
	return nil
}

func (x *GetDisciplinesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetStudentWorksByTaskResponse_StudentWork struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentName       string                 `protobuf:"bytes,2,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	StudentSurname    string                 `protobuf:"bytes,3,opt,name=student_surname,json=studentSurname,proto3" json:"student_surname,omitempty"`
	StudentPatronymic string                 `protobuf:"bytes,4,opt,name=student_patronymic,json=studentPatronymic,proto3" json:"student_patronymic,omitempty"`
	StudentEmail      string                 `protobuf:"bytes,5,opt,name=student_email,json=studentEmail,proto3" json:"student_email,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetStudentWorksByTaskResponse_StudentWork) Reset() {
	*x = GetStudentWorksByTaskResponse_StudentWork{}
	mi := &file_proto_work_work_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentWorksByTaskResponse_StudentWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentWorksByTaskResponse_StudentWork) ProtoMessage() {}

func (x *GetStudentWorksByTaskResponse_StudentWork) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentWorksByTaskResponse_StudentWork.ProtoReflect.Descriptor instead.
func (*GetStudentWorksByTaskResponse_StudentWork) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetStudentWorksByTaskResponse_StudentWork) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetStudentWorksByTaskResponse_StudentWork) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *GetStudentWorksByTaskResponse_StudentWork) GetStudentSurname() string {
	if x != nil {
		return x.StudentSurname
	}
	return ""
}

func (x *GetStudentWorksByTaskResponse_StudentWork) GetStudentPatronymic() string {
	if x != nil {
		return x.StudentPatronymic
	}
	return ""
}

func (x *GetStudentWorksByTaskResponse_StudentWork) GetStudentEmail() string {
	if x != nil {
		return x.StudentEmail
	}
	return ""
}

type GetAssistantsByDisciplineResponse_Assistant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surname       string                 `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
	Patronymic    string                 `protobuf:"bytes,4,opt,name=patronymic,proto3" json:"patronymic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssistantsByDisciplineResponse_Assistant) Reset() {
	*x = GetAssistantsByDisciplineResponse_Assistant{}
	mi := &file_proto_work_work_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssistantsByDisciplineResponse_Assistant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssistantsByDisciplineResponse_Assistant) ProtoMessage() {}

func (x *GetAssistantsByDisciplineResponse_Assistant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssistantsByDisciplineResponse_Assistant.ProtoReflect.Descriptor instead.
func (*GetAssistantsByDisciplineResponse_Assistant) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetAssistantsByDisciplineResponse_Assistant) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetAssistantsByDisciplineResponse_Assistant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAssistantsByDisciplineResponse_Assistant) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *GetAssistantsByDisciplineResponse_Assistant) GetPatronymic() string {
	if x != nil {
		return x.Patronymic
	}
	return ""
}

type AssignAssistantsToWorksRequest_Assignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        int32                  `protobuf:"varint,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	AssistantId   int32                  `protobuf:"varint,2,opt,name=assistant_id,json=assistantId,proto3" json:"assistant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignAssistantsToWorksRequest_Assignment) Reset() {
	*x = AssignAssistantsToWorksRequest_Assignment{}
	mi := &file_proto_work_work_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignAssistantsToWorksRequest_Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAssistantsToWorksRequest_Assignment) ProtoMessage() {}

func (x *AssignAssistantsToWorksRequest_Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAssistantsToWorksRequest_Assignment.ProtoReflect.Descriptor instead.
func (*AssignAssistantsToWorksRequest_Assignment) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{6, 0}
}

func (x *AssignAssistantsToWorksRequest_Assignment) GetWorkId() int32 {
	if x != nil {
		return x.WorkId
	}
	return 0
}

func (x *AssignAssistantsToWorksRequest_Assignment) GetAssistantId() int32 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

type GetTasksForSeminaristResponse_Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Deadline      string                 `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksForSeminaristResponse_Task) Reset() {
	*x = GetTasksForSeminaristResponse_Task{}
	mi := &file_proto_work_work_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksForSeminaristResponse_Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksForSeminaristResponse_Task) ProtoMessage() {}

func (x *GetTasksForSeminaristResponse_Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksForSeminaristResponse_Task.ProtoReflect.Descriptor instead.
func (*GetTasksForSeminaristResponse_Task) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{9, 0}
}

func (x *GetTasksForSeminaristResponse_Task) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTasksForSeminaristResponse_Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetTasksForSeminaristResponse_Task) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

type GetStudentWorksForSeminaristResponse_StudentWork struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StudentName   string                 `protobuf:"bytes,4,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	TaskId        int32                  `protobuf:"varint,5,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentWorksForSeminaristResponse_StudentWork) Reset() {
	*x = GetStudentWorksForSeminaristResponse_StudentWork{}
	mi := &file_proto_work_work_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentWorksForSeminaristResponse_StudentWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentWorksForSeminaristResponse_StudentWork) ProtoMessage() {}

func (x *GetStudentWorksForSeminaristResponse_StudentWork) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentWorksForSeminaristResponse_StudentWork.ProtoReflect.Descriptor instead.
func (*GetStudentWorksForSeminaristResponse_StudentWork) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{11, 0}
}

func (x *GetStudentWorksForSeminaristResponse_StudentWork) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetStudentWorksForSeminaristResponse_StudentWork) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetStudentWorksForSeminaristResponse_StudentWork) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetStudentWorksForSeminaristResponse_StudentWork) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *GetStudentWorksForSeminaristResponse_StudentWork) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type GetGroupsResponse_Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsResponse_Group) Reset() {
	*x = GetGroupsResponse_Group{}
	mi := &file_proto_work_work_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsResponse_Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsResponse_Group) ProtoMessage() {}

func (x *GetGroupsResponse_Group) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsResponse_Group.ProtoReflect.Descriptor instead.
func (*GetGroupsResponse_Group) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{36, 0}
}

func (x *GetGroupsResponse_Group) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetGroupsResponse_Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDisciplinesResponse_Discipline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDisciplinesResponse_Discipline) Reset() {
	*x = GetDisciplinesResponse_Discipline{}
	mi := &file_proto_work_work_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDisciplinesResponse_Discipline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisciplinesResponse_Discipline) ProtoMessage() {}

func (x *GetDisciplinesResponse_Discipline) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_work_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDisciplinesResponse_Discipline.ProtoReflect.Descriptor instead.
func (*GetDisciplinesResponse_Discipline) Descriptor() ([]byte, []int) {
	return file_proto_work_work_proto_rawDescGZIP(), []int{38, 0}
}

func (x *GetDisciplinesResponse_Discipline) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetDisciplinesResponse_Discipline) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_work_work_proto protoreflect.FileDescriptor

const file_proto_work_work_proto_rawDesc = "" +
	"\n" +
	"\x15proto/work/work.proto\x12\x04work\"g\n" +
	"\x11UpdateWorkRequest\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\x05R\x06workId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fassistant_id\x18\x03 \x01(\x05R\vassistantId\"*\n" +
	"\x12UpdateWorkResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"7\n" +
	"\x1cGetStudentWorksByTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\"\xbc\x02\n" +
	"\x1dGetStudentWorksByTaskResponse\x12E\n" +
	"\x05works\x18\x01 \x03(\v2/.work.GetStudentWorksByTaskResponse.StudentWorkR\x05works\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x1a\xbd\x01\n" +
	"\vStudentWork\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12!\n" +
	"\fstudent_name\x18\x02 \x01(\tR\vstudentName\x12'\n" +
	"\x0fstudent_surname\x18\x03 \x01(\tR\x0estudentSurname\x12-\n" +
	"\x12student_patronymic\x18\x04 \x01(\tR\x11studentPatronymic\x12#\n" +
	"\rstudent_email\x18\x05 \x01(\tR\fstudentEmail\"G\n" +
	" GetAssistantsByDisciplineRequest\x12#\n" +
	"\rdiscipline_id\x18\x01 \x01(\x05R\fdisciplineId\"\xf7\x01\n" +
	"!GetAssistantsByDisciplineResponse\x12Q\n" +
	"\n" +
	"assistants\x18\x01 \x03(\v21.work.GetAssistantsByDisciplineResponse.AssistantR\n" +
	"assistants\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x1ai\n" +
	"\tAssistant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x03 \x01(\tR\asurname\x12\x1e\n" +
	"\n" +
	"patronymic\x18\x04 \x01(\tR\n" +
	"patronymic\"\xbd\x01\n" +
	"\x1eAssignAssistantsToWorksRequest\x12Q\n" +
	"\vassignments\x18\x01 \x03(\v2/.work.AssignAssistantsToWorksRequest.AssignmentR\vassignments\x1aH\n" +
	"\n" +
	"Assignment\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\x05R\x06workId\x12!\n" +
	"\fassistant_id\x18\x02 \x01(\x05R\vassistantId\"Q\n" +
	"\x1fAssignAssistantsToWorksResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"C\n" +
	"\x1cGetTasksForSeminaristRequest\x12#\n" +
	"\rseminarist_id\x18\x01 \x01(\tR\fseminaristId\"\xbf\x01\n" +
	"\x1dGetTasksForSeminaristResponse\x12>\n" +
	"\x05tasks\x18\x01 \x03(\v2(.work.GetTasksForSeminaristResponse.TaskR\x05tasks\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x1aH\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bdeadline\x18\x03 \x01(\tR\bdeadline\"J\n" +
	"#GetStudentWorksForSeminaristRequest\x12#\n" +
	"\rseminarist_id\x18\x01 \x01(\tR\fseminaristId\"\x9b\x02\n" +
	"$GetStudentWorksForSeminaristResponse\x12L\n" +
	"\x05works\x18\x01 \x03(\v26.work.GetStudentWorksForSeminaristResponse.StudentWorkR\x05works\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x1a\x8e\x01\n" +
	"\vStudentWork\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12!\n" +
	"\fstudent_name\x18\x04 \x01(\tR\vstudentName\x12\x17\n" +
	"\atask_id\x18\x05 \x01(\x05R\x06taskId\"0\n" +
	"\x15GetTaskDetailsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\"\xe4\x02\n" +
	"\x16GetTaskDetailsResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bdeadline\x18\x03 \x01(\tR\bdeadline\x12\x1d\n" +
	"\n" +
	"group_name\x18\x04 \x01(\tR\tgroupName\x12'\n" +
	"\x0fdiscipline_name\x18\x05 \x01(\tR\x0edisciplineName\x12\x1f\n" +
	"\vlector_name\x18\x06 \x01(\tR\n" +
	"lectorName\x12%\n" +
	"\x0elector_surname\x18\a \x01(\tR\rlectorSurname\x12+\n" +
	"\x11lector_patronymic\x18\b \x01(\tR\x10lectorPatronymic\x12#\n" +
	"\rdiscipline_id\x18\t \x01(\x05R\fdisciplineId\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\"~\n" +
	"#UpdateTaskGroupAndDisciplineRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x05R\agroupId\x12#\n" +
	"\rdiscipline_id\x18\x03 \x01(\x05R\fdisciplineId\"V\n" +
	"$UpdateTaskGroupAndDisciplineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"7\n" +
	"\x18GetTasksForLectorRequest\x12\x1b\n" +
	"\tlector_id\x18\x01 \x01(\x05R\blectorId\"H\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bdeadline\x18\x03 \x01(\tR\bdeadline\"S\n" +
	"\x19GetTasksForLectorResponse\x12 \n" +
	"\x05tasks\x18\x01 \x03(\v2\n" +
	".work.TaskR\x05tasks\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\",\n" +
	"\x11DeleteTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\"D\n" +
	"\x12DeleteTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"D\n" +
	"\x13SetTaskTitleRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"F\n" +
	"\x14SetTaskTitleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"V\n" +
	"\x19SetTaskDescriptionRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"L\n" +
	"\x1aSetTaskDescriptionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"M\n" +
	"\x16SetTaskDeadlineRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12\x1a\n" +
	"\bdeadline\x18\x02 \x01(\tR\bdeadline\"I\n" +
	"\x17SetTaskDeadlineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xe5\x01\n" +
	"\x11CreateWorkRequest\x12\x1b\n" +
	"\tlector_id\x18\x01 \x01(\x05R\blectorId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x05R\agroupId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bdeadline\x18\x05 \x01(\tR\bdeadline\x12#\n" +
	"\rdiscipline_id\x18\x06 \x01(\x05R\fdisciplineId\x12\x1f\n" +
	"\vcontent_url\x18\a \x01(\tR\n" +
	"contentUrl\"C\n" +
	"\x12CreateWorkResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\".\n" +
	"\x13LoadTaskNameRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\"B\n" +
	"\x14LoadTaskNameResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"5\n" +
	"\x1aLoadTaskDescriptionRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\"U\n" +
	"\x1bLoadTaskDescriptionResponse\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"2\n" +
	"\x17LoadTaskDeadlineRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\"L\n" +
	"\x18LoadTaskDeadlineResponse\x12\x1a\n" +
	"\bdeadline\x18\x01 \x01(\tR\bdeadline\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"/\n" +
	"\x10GetGroupsRequest\x12\x1b\n" +
	"\tlector_id\x18\x01 \x01(\x05R\blectorId\"\x8d\x01\n" +
	"\x11GetGroupsResponse\x125\n" +
	"\x06groups\x18\x01 \x03(\v2\x1d.work.GetGroupsResponse.GroupR\x06groups\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x1a+\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"4\n" +
	"\x15GetDisciplinesRequest\x12\x1b\n" +
	"\tlector_id\x18\x01 \x01(\x05R\blectorId\"\xab\x01\n" +
	"\x16GetDisciplinesResponse\x12I\n" +
	"\vdisciplines\x18\x01 \x03(\v2'.work.GetDisciplinesResponse.DisciplineR\vdisciplines\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x1a0\n" +
	"\n" +
	"Discipline\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\x8c\r\n" +
	"\vWorkService\x12V\n" +
	"\x11GetTasksForLector\x12\x1e.work.GetTasksForLectorRequest\x1a\x1f.work.GetTasksForLectorResponse\"\x00\x12A\n" +
	"\n" +
	"DeleteTask\x12\x17.work.DeleteTaskRequest\x1a\x18.work.DeleteTaskResponse\"\x00\x12G\n" +
	"\fSetTaskTitle\x12\x19.work.SetTaskTitleRequest\x1a\x1a.work.SetTaskTitleResponse\"\x00\x12Y\n" +
	"\x12SetTaskDescription\x12\x1f.work.SetTaskDescriptionRequest\x1a .work.SetTaskDescriptionResponse\"\x00\x12P\n" +
	"\x0fSetTaskDeadline\x12\x1c.work.SetTaskDeadlineRequest\x1a\x1d.work.SetTaskDeadlineResponse\"\x00\x12A\n" +
	"\n" +
	"CreateWork\x12\x17.work.CreateWorkRequest\x1a\x18.work.CreateWorkResponse\"\x00\x12G\n" +
	"\fLoadTaskName\x12\x19.work.LoadTaskNameRequest\x1a\x1a.work.LoadTaskNameResponse\"\x00\x12\\\n" +
	"\x13LoadTaskDescription\x12 .work.LoadTaskDescriptionRequest\x1a!.work.LoadTaskDescriptionResponse\"\x00\x12S\n" +
	"\x10LoadTaskDeadline\x12\x1d.work.LoadTaskDeadlineRequest\x1a\x1e.work.LoadTaskDeadlineResponse\"\x00\x12<\n" +
	"\tGetGroups\x12\x16.work.GetGroupsRequest\x1a\x17.work.GetGroupsResponse\x12K\n" +
	"\x0eGetDisciplines\x12\x1b.work.GetDisciplinesRequest\x1a\x1c.work.GetDisciplinesResponse\x12M\n" +
	"\x0eGetTaskDetails\x12\x1b.work.GetTaskDetailsRequest\x1a\x1c.work.GetTaskDetailsResponse\"\x00\x12w\n" +
	"\x1cUpdateTaskGroupAndDiscipline\x12).work.UpdateTaskGroupAndDisciplineRequest\x1a*.work.UpdateTaskGroupAndDisciplineResponse\"\x00\x12w\n" +
	"\x1cGetStudentWorksForSeminarist\x12).work.GetStudentWorksForSeminaristRequest\x1a*.work.GetStudentWorksForSeminaristResponse\"\x00\x12b\n" +
	"\x15GetTasksForSeminarist\x12\".work.GetTasksForSeminaristRequest\x1a#.work.GetTasksForSeminaristResponse\"\x00\x12b\n" +
	"\x15GetStudentWorksByTask\x12\".work.GetStudentWorksByTaskRequest\x1a#.work.GetStudentWorksByTaskResponse\"\x00\x12n\n" +
	"\x19GetAssistantsByDiscipline\x12&.work.GetAssistantsByDisciplineRequest\x1a'.work.GetAssistantsByDisciplineResponse\"\x00\x12h\n" +
	"\x17AssignAssistantsToWorks\x12$.work.AssignAssistantsToWorksRequest\x1a%.work.AssignAssistantsToWorksResponse\"\x00\x12?\n" +
	"\n" +
	"UpdateWork\x12\x17.work.UpdateWorkRequest\x1a\x18.work.UpdateWorkResponseB\x13Z\x11./proto/work;workb\x06proto3"

var (
	file_proto_work_work_proto_rawDescOnce sync.Once
	file_proto_work_work_proto_rawDescData []byte
)

func file_proto_work_work_proto_rawDescGZIP() []byte {
	file_proto_work_work_proto_rawDescOnce.Do(func() {
		file_proto_work_work_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_work_work_proto_rawDesc), len(file_proto_work_work_proto_rawDesc)))
	})
	return file_proto_work_work_proto_rawDescData
}

var file_proto_work_work_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_proto_work_work_proto_goTypes = []any{
	(*UpdateWorkRequest)(nil),                                // 0: work.UpdateWorkRequest
	(*UpdateWorkResponse)(nil),                               // 1: work.UpdateWorkResponse
	(*GetStudentWorksByTaskRequest)(nil),                     // 2: work.GetStudentWorksByTaskRequest
	(*GetStudentWorksByTaskResponse)(nil),                    // 3: work.GetStudentWorksByTaskResponse
	(*GetAssistantsByDisciplineRequest)(nil),                 // 4: work.GetAssistantsByDisciplineRequest
	(*GetAssistantsByDisciplineResponse)(nil),                // 5: work.GetAssistantsByDisciplineResponse
	(*AssignAssistantsToWorksRequest)(nil),                   // 6: work.AssignAssistantsToWorksRequest
	(*AssignAssistantsToWorksResponse)(nil),                  // 7: work.AssignAssistantsToWorksResponse
	(*GetTasksForSeminaristRequest)(nil),                     // 8: work.GetTasksForSeminaristRequest
	(*GetTasksForSeminaristResponse)(nil),                    // 9: work.GetTasksForSeminaristResponse
	(*GetStudentWorksForSeminaristRequest)(nil),              // 10: work.GetStudentWorksForSeminaristRequest
	(*GetStudentWorksForSeminaristResponse)(nil),             // 11: work.GetStudentWorksForSeminaristResponse
	(*GetTaskDetailsRequest)(nil),                            // 12: work.GetTaskDetailsRequest
	(*GetTaskDetailsResponse)(nil),                           // 13: work.GetTaskDetailsResponse
	(*UpdateTaskGroupAndDisciplineRequest)(nil),              // 14: work.UpdateTaskGroupAndDisciplineRequest
	(*UpdateTaskGroupAndDisciplineResponse)(nil),             // 15: work.UpdateTaskGroupAndDisciplineResponse
	(*GetTasksForLectorRequest)(nil),                         // 16: work.GetTasksForLectorRequest
	(*Task)(nil),                                             // 17: work.Task
	(*GetTasksForLectorResponse)(nil),                        // 18: work.GetTasksForLectorResponse
	(*DeleteTaskRequest)(nil),                                // 19: work.DeleteTaskRequest
	(*DeleteTaskResponse)(nil),                               // 20: work.DeleteTaskResponse
	(*SetTaskTitleRequest)(nil),                              // 21: work.SetTaskTitleRequest
	(*SetTaskTitleResponse)(nil),                             // 22: work.SetTaskTitleResponse
	(*SetTaskDescriptionRequest)(nil),                        // 23: work.SetTaskDescriptionRequest
	(*SetTaskDescriptionResponse)(nil),                       // 24: work.SetTaskDescriptionResponse
	(*SetTaskDeadlineRequest)(nil),                           // 25: work.SetTaskDeadlineRequest
	(*SetTaskDeadlineResponse)(nil),                          // 26: work.SetTaskDeadlineResponse
	(*CreateWorkRequest)(nil),                                // 27: work.CreateWorkRequest
	(*CreateWorkResponse)(nil),                               // 28: work.CreateWorkResponse
	(*LoadTaskNameRequest)(nil),                              // 29: work.LoadTaskNameRequest
	(*LoadTaskNameResponse)(nil),                             // 30: work.LoadTaskNameResponse
	(*LoadTaskDescriptionRequest)(nil),                       // 31: work.LoadTaskDescriptionRequest
	(*LoadTaskDescriptionResponse)(nil),                      // 32: work.LoadTaskDescriptionResponse
	(*LoadTaskDeadlineRequest)(nil),                          // 33: work.LoadTaskDeadlineRequest
	(*LoadTaskDeadlineResponse)(nil),                         // 34: work.LoadTaskDeadlineResponse
	(*GetGroupsRequest)(nil),                                 // 35: work.GetGroupsRequest
	(*GetGroupsResponse)(nil),                                // 36: work.GetGroupsResponse
	(*GetDisciplinesRequest)(nil),                            // 37: work.GetDisciplinesRequest
	(*GetDisciplinesResponse)(nil),                           // 38: work.GetDisciplinesResponse
	(*GetStudentWorksByTaskResponse_StudentWork)(nil),        // 39: work.GetStudentWorksByTaskResponse.StudentWork
	(*GetAssistantsByDisciplineResponse_Assistant)(nil),      // 40: work.GetAssistantsByDisciplineResponse.Assistant
	(*AssignAssistantsToWorksRequest_Assignment)(nil),        // 41: work.AssignAssistantsToWorksRequest.Assignment
	(*GetTasksForSeminaristResponse_Task)(nil),               // 42: work.GetTasksForSeminaristResponse.Task
	(*GetStudentWorksForSeminaristResponse_StudentWork)(nil), // 43: work.GetStudentWorksForSeminaristResponse.StudentWork
	(*GetGroupsResponse_Group)(nil),                          // 44: work.GetGroupsResponse.Group
	(*GetDisciplinesResponse_Discipline)(nil),                // 45: work.GetDisciplinesResponse.Discipline
}
var file_proto_work_work_proto_depIdxs = []int32{
	39, // 0: work.GetStudentWorksByTaskResponse.works:type_name -> work.GetStudentWorksByTaskResponse.StudentWork
	40, // 1: work.GetAssistantsByDisciplineResponse.assistants:type_name -> work.GetAssistantsByDisciplineResponse.Assistant
	41, // 2: work.AssignAssistantsToWorksRequest.assignments:type_name -> work.AssignAssistantsToWorksRequest.Assignment
	42, // 3: work.GetTasksForSeminaristResponse.tasks:type_name -> work.GetTasksForSeminaristResponse.Task
	43, // 4: work.GetStudentWorksForSeminaristResponse.works:type_name -> work.GetStudentWorksForSeminaristResponse.StudentWork
	17, // 5: work.GetTasksForLectorResponse.tasks:type_name -> work.Task
	44, // 6: work.GetGroupsResponse.groups:type_name -> work.GetGroupsResponse.Group
	45, // 7: work.GetDisciplinesResponse.disciplines:type_name -> work.GetDisciplinesResponse.Discipline
	16, // 8: work.WorkService.GetTasksForLector:input_type -> work.GetTasksForLectorRequest
	19, // 9: work.WorkService.DeleteTask:input_type -> work.DeleteTaskRequest
	21, // 10: work.WorkService.SetTaskTitle:input_type -> work.SetTaskTitleRequest
	23, // 11: work.WorkService.SetTaskDescription:input_type -> work.SetTaskDescriptionRequest
	25, // 12: work.WorkService.SetTaskDeadline:input_type -> work.SetTaskDeadlineRequest
	27, // 13: work.WorkService.CreateWork:input_type -> work.CreateWorkRequest
	29, // 14: work.WorkService.LoadTaskName:input_type -> work.LoadTaskNameRequest
	31, // 15: work.WorkService.LoadTaskDescription:input_type -> work.LoadTaskDescriptionRequest
	33, // 16: work.WorkService.LoadTaskDeadline:input_type -> work.LoadTaskDeadlineRequest
	35, // 17: work.WorkService.GetGroups:input_type -> work.GetGroupsRequest
	37, // 18: work.WorkService.GetDisciplines:input_type -> work.GetDisciplinesRequest
	12, // 19: work.WorkService.GetTaskDetails:input_type -> work.GetTaskDetailsRequest
	14, // 20: work.WorkService.UpdateTaskGroupAndDiscipline:input_type -> work.UpdateTaskGroupAndDisciplineRequest
	10, // 21: work.WorkService.GetStudentWorksForSeminarist:input_type -> work.GetStudentWorksForSeminaristRequest
	8,  // 22: work.WorkService.GetTasksForSeminarist:input_type -> work.GetTasksForSeminaristRequest
	2,  // 23: work.WorkService.GetStudentWorksByTask:input_type -> work.GetStudentWorksByTaskRequest
	4,  // 24: work.WorkService.GetAssistantsByDiscipline:input_type -> work.GetAssistantsByDisciplineRequest
	6,  // 25: work.WorkService.AssignAssistantsToWorks:input_type -> work.AssignAssistantsToWorksRequest
	0,  // 26: work.WorkService.UpdateWork:input_type -> work.UpdateWorkRequest
	18, // 27: work.WorkService.GetTasksForLector:output_type -> work.GetTasksForLectorResponse
	20, // 28: work.WorkService.DeleteTask:output_type -> work.DeleteTaskResponse
	22, // 29: work.WorkService.SetTaskTitle:output_type -> work.SetTaskTitleResponse
	24, // 30: work.WorkService.SetTaskDescription:output_type -> work.SetTaskDescriptionResponse
	26, // 31: work.WorkService.SetTaskDeadline:output_type -> work.SetTaskDeadlineResponse
	28, // 32: work.WorkService.CreateWork:output_type -> work.CreateWorkResponse
	30, // 33: work.WorkService.LoadTaskName:output_type -> work.LoadTaskNameResponse
	32, // 34: work.WorkService.LoadTaskDescription:output_type -> work.LoadTaskDescriptionResponse
	34, // 35: work.WorkService.LoadTaskDeadline:output_type -> work.LoadTaskDeadlineResponse
	36, // 36: work.WorkService.GetGroups:output_type -> work.GetGroupsResponse
	38, // 37: work.WorkService.GetDisciplines:output_type -> work.GetDisciplinesResponse
	13, // 38: work.WorkService.GetTaskDetails:output_type -> work.GetTaskDetailsResponse
	15, // 39: work.WorkService.UpdateTaskGroupAndDiscipline:output_type -> work.UpdateTaskGroupAndDisciplineResponse
	11, // 40: work.WorkService.GetStudentWorksForSeminarist:output_type -> work.GetStudentWorksForSeminaristResponse
	9,  // 41: work.WorkService.GetTasksForSeminarist:output_type -> work.GetTasksForSeminaristResponse
	3,  // 42: work.WorkService.GetStudentWorksByTask:output_type -> work.GetStudentWorksByTaskResponse
	5,  // 43: work.WorkService.GetAssistantsByDiscipline:output_type -> work.GetAssistantsByDisciplineResponse
	7,  // 44: work.WorkService.AssignAssistantsToWorks:output_type -> work.AssignAssistantsToWorksResponse
	1,  // 45: work.WorkService.UpdateWork:output_type -> work.UpdateWorkResponse
	27, // [27:46] is the sub-list for method output_type
	8,  // [8:27] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_work_work_proto_init() }
func file_proto_work_work_proto_init() {
	if File_proto_work_work_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_work_work_proto_rawDesc), len(file_proto_work_work_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_work_work_proto_goTypes,
		DependencyIndexes: file_proto_work_work_proto_depIdxs,
		MessageInfos:      file_proto_work_work_proto_msgTypes,
	}.Build()
	File_proto_work_work_proto = out.File
	file_proto_work_work_proto_goTypes = nil
	file_proto_work_work_proto_depIdxs = nil
}
