// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/workassignment/workassignment.proto

package workassignment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWorksForAssistantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   int32                  `protobuf:"varint,1,opt,name=assistant_id,json=assistantId,proto3" json:"assistant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorksForAssistantRequest) Reset() {
	*x = GetWorksForAssistantRequest{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorksForAssistantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorksForAssistantRequest) ProtoMessage() {}

func (x *GetWorksForAssistantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorksForAssistantRequest.ProtoReflect.Descriptor instead.
func (*GetWorksForAssistantRequest) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{0}
}

func (x *GetWorksForAssistantRequest) GetAssistantId() int32 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

type GetWorksForAssistantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Works         []*WorkAssignment      `protobuf:"bytes,1,rep,name=works,proto3" json:"works,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorksForAssistantResponse) Reset() {
	*x = GetWorksForAssistantResponse{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorksForAssistantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorksForAssistantResponse) ProtoMessage() {}

func (x *GetWorksForAssistantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorksForAssistantResponse.ProtoReflect.Descriptor instead.
func (*GetWorksForAssistantResponse) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{1}
}

func (x *GetWorksForAssistantResponse) GetWorks() []*WorkAssignment {
	if x != nil {
		return x.Works
	}
	return nil
}

func (x *GetWorksForAssistantResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetWorkDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        int32                  `protobuf:"varint,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkDetailsRequest) Reset() {
	*x = GetWorkDetailsRequest{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkDetailsRequest) ProtoMessage() {}

func (x *GetWorkDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetWorkDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{2}
}

func (x *GetWorkDetailsRequest) GetWorkId() int32 {
	if x != nil {
		return x.WorkId
	}
	return 0
}

type GetWorkDetailsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkId          int32                  `protobuf:"varint,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	TaskTitle       string                 `protobuf:"bytes,2,opt,name=task_title,json=taskTitle,proto3" json:"task_title,omitempty"`
	TaskDescription string                 `protobuf:"bytes,3,opt,name=task_description,json=taskDescription,proto3" json:"task_description,omitempty"`
	TaskDeadline    string                 `protobuf:"bytes,4,opt,name=task_deadline,json=taskDeadline,proto3" json:"task_deadline,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	ContentUrl      string                 `protobuf:"bytes,7,opt,name=content_url,json=contentUrl,proto3" json:"content_url,omitempty"`
	Error           string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetWorkDetailsResponse) Reset() {
	*x = GetWorkDetailsResponse{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkDetailsResponse) ProtoMessage() {}

func (x *GetWorkDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetWorkDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorkDetailsResponse) GetWorkId() int32 {
	if x != nil {
		return x.WorkId
	}
	return 0
}

func (x *GetWorkDetailsResponse) GetTaskTitle() string {
	if x != nil {
		return x.TaskTitle
	}
	return ""
}

func (x *GetWorkDetailsResponse) GetTaskDescription() string {
	if x != nil {
		return x.TaskDescription
	}
	return ""
}

func (x *GetWorkDetailsResponse) GetTaskDeadline() string {
	if x != nil {
		return x.TaskDeadline
	}
	return ""
}

func (x *GetWorkDetailsResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetWorkDetailsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetWorkDetailsResponse) GetContentUrl() string {
	if x != nil {
		return x.ContentUrl
	}
	return ""
}

func (x *GetWorkDetailsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WorkAssignment struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WorkId            int32                  `protobuf:"varint,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	TaskId            int32                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskTitle         string                 `protobuf:"bytes,3,opt,name=task_title,json=taskTitle,proto3" json:"task_title,omitempty"`
	StudentId         int32                  `protobuf:"varint,4,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StudentEmail      string                 `protobuf:"bytes,5,opt,name=student_email,json=studentEmail,proto3" json:"student_email,omitempty"`
	StudentName       string                 `protobuf:"bytes,6,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	StudentSurname    string                 `protobuf:"bytes,7,opt,name=student_surname,json=studentSurname,proto3" json:"student_surname,omitempty"`
	StudentPatronymic string                 `protobuf:"bytes,8,opt,name=student_patronymic,json=studentPatronymic,proto3" json:"student_patronymic,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WorkAssignment) Reset() {
	*x = WorkAssignment{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkAssignment) ProtoMessage() {}

func (x *WorkAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkAssignment.ProtoReflect.Descriptor instead.
func (*WorkAssignment) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{4}
}

func (x *WorkAssignment) GetWorkId() int32 {
	if x != nil {
		return x.WorkId
	}
	return 0
}

func (x *WorkAssignment) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *WorkAssignment) GetTaskTitle() string {
	if x != nil {
		return x.TaskTitle
	}
	return ""
}

func (x *WorkAssignment) GetStudentId() int32 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *WorkAssignment) GetStudentEmail() string {
	if x != nil {
		return x.StudentEmail
	}
	return ""
}

func (x *WorkAssignment) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *WorkAssignment) GetStudentSurname() string {
	if x != nil {
		return x.StudentSurname
	}
	return ""
}

func (x *WorkAssignment) GetStudentPatronymic() string {
	if x != nil {
		return x.StudentPatronymic
	}
	return ""
}

var File_proto_workassignment_workassignment_proto protoreflect.FileDescriptor

const file_proto_workassignment_workassignment_proto_rawDesc = "" +
	"\n" +
	")proto/workassignment/workassignment.proto\x12\x0eworkassignment\"@\n" +
	"\x1bGetWorksForAssistantRequest\x12!\n" +
	"\fassistant_id\x18\x01 \x01(\x05R\vassistantId\"j\n" +
	"\x1cGetWorksForAssistantResponse\x124\n" +
	"\x05works\x18\x01 \x03(\v2\x1e.workassignment.WorkAssignmentR\x05works\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"0\n" +
	"\x15GetWorkDetailsRequest\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\x05R\x06workId\"\x8e\x02\n" +
	"\x16GetWorkDetailsResponse\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\x05R\x06workId\x12\x1d\n" +
	"\n" +
	"task_title\x18\x02 \x01(\tR\ttaskTitle\x12)\n" +
	"\x10task_description\x18\x03 \x01(\tR\x0ftaskDescription\x12#\n" +
	"\rtask_deadline\x18\x04 \x01(\tR\ftaskDeadline\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1f\n" +
	"\vcontent_url\x18\a \x01(\tR\n" +
	"contentUrl\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"\xa0\x02\n" +
	"\x0eWorkAssignment\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\x05R\x06workId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x05R\x06taskId\x12\x1d\n" +
	"\n" +
	"task_title\x18\x03 \x01(\tR\ttaskTitle\x12\x1d\n" +
	"\n" +
	"student_id\x18\x04 \x01(\x05R\tstudentId\x12#\n" +
	"\rstudent_email\x18\x05 \x01(\tR\fstudentEmail\x12!\n" +
	"\fstudent_name\x18\x06 \x01(\tR\vstudentName\x12'\n" +
	"\x0fstudent_surname\x18\a \x01(\tR\x0estudentSurname\x12-\n" +
	"\x12student_patronymic\x18\b \x01(\tR\x11studentPatronymic2\xeb\x01\n" +
	"\x15WorkAssignmentService\x12q\n" +
	"\x14GetWorksForAssistant\x12+.workassignment.GetWorksForAssistantRequest\x1a,.workassignment.GetWorksForAssistantResponse\x12_\n" +
	"\x0eGetWorkDetails\x12%.workassignment.GetWorkDetailsRequest\x1a&.workassignment.GetWorkDetailsResponseB'Z%./proto/workassignment;workassignmentb\x06proto3"

var (
	file_proto_workassignment_workassignment_proto_rawDescOnce sync.Once
	file_proto_workassignment_workassignment_proto_rawDescData []byte
)

func file_proto_workassignment_workassignment_proto_rawDescGZIP() []byte {
	file_proto_workassignment_workassignment_proto_rawDescOnce.Do(func() {
		file_proto_workassignment_workassignment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_workassignment_workassignment_proto_rawDesc), len(file_proto_workassignment_workassignment_proto_rawDesc)))
	})
	return file_proto_workassignment_workassignment_proto_rawDescData
}

var file_proto_workassignment_workassignment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_workassignment_workassignment_proto_goTypes = []any{
	(*GetWorksForAssistantRequest)(nil),  // 0: workassignment.GetWorksForAssistantRequest
	(*GetWorksForAssistantResponse)(nil), // 1: workassignment.GetWorksForAssistantResponse
	(*GetWorkDetailsRequest)(nil),        // 2: workassignment.GetWorkDetailsRequest
	(*GetWorkDetailsResponse)(nil),       // 3: workassignment.GetWorkDetailsResponse
	(*WorkAssignment)(nil),               // 4: workassignment.WorkAssignment
}
var file_proto_workassignment_workassignment_proto_depIdxs = []int32{
	4, // 0: workassignment.GetWorksForAssistantResponse.works:type_name -> workassignment.WorkAssignment
	0, // 1: workassignment.WorkAssignmentService.GetWorksForAssistant:input_type -> workassignment.GetWorksForAssistantRequest
	2, // 2: workassignment.WorkAssignmentService.GetWorkDetails:input_type -> workassignment.GetWorkDetailsRequest
	1, // 3: workassignment.WorkAssignmentService.GetWorksForAssistant:output_type -> workassignment.GetWorksForAssistantResponse
	3, // 4: workassignment.WorkAssignmentService.GetWorkDetails:output_type -> workassignment.GetWorkDetailsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_workassignment_workassignment_proto_init() }
func file_proto_workassignment_workassignment_proto_init() {
	if File_proto_workassignment_workassignment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_workassignment_workassignment_proto_rawDesc), len(file_proto_workassignment_workassignment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_workassignment_workassignment_proto_goTypes,
		DependencyIndexes: file_proto_workassignment_workassignment_proto_depIdxs,
		MessageInfos:      file_proto_workassignment_workassignment_proto_msgTypes,
	}.Build()
	File_proto_workassignment_workassignment_proto = out.File
	file_proto_workassignment_workassignment_proto_goTypes = nil
	file_proto_workassignment_workassignment_proto_depIdxs = nil
}
