// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/workassignment/workassignment.proto

package workassignment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateUploadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        int32                  `protobuf:"varint,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateUploadURLRequest) Reset() {
	*x = GenerateUploadURLRequest{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUploadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUploadURLRequest) ProtoMessage() {}

func (x *GenerateUploadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUploadURLRequest.ProtoReflect.Descriptor instead.
func (*GenerateUploadURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateUploadURLRequest) GetWorkId() int32 {
	if x != nil {
		return x.WorkId
	}
	return 0
}

func (x *GenerateUploadURLRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GenerateUploadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateUploadURLResponse) Reset() {
	*x = GenerateUploadURLResponse{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUploadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUploadURLResponse) ProtoMessage() {}

func (x *GenerateUploadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUploadURLResponse.ProtoReflect.Descriptor instead.
func (*GenerateUploadURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateUploadURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GenerateUploadURLResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetWorksForAssistantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   int32                  `protobuf:"varint,1,opt,name=assistant_id,json=assistantId,proto3" json:"assistant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorksForAssistantRequest) Reset() {
	*x = GetWorksForAssistantRequest{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorksForAssistantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorksForAssistantRequest) ProtoMessage() {}

func (x *GetWorksForAssistantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorksForAssistantRequest.ProtoReflect.Descriptor instead.
func (*GetWorksForAssistantRequest) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{2}
}

func (x *GetWorksForAssistantRequest) GetAssistantId() int32 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

type GetWorksForAssistantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Works         []*WorkAssignment      `protobuf:"bytes,1,rep,name=works,proto3" json:"works,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorksForAssistantResponse) Reset() {
	*x = GetWorksForAssistantResponse{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorksForAssistantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorksForAssistantResponse) ProtoMessage() {}

func (x *GetWorksForAssistantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorksForAssistantResponse.ProtoReflect.Descriptor instead.
func (*GetWorksForAssistantResponse) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorksForAssistantResponse) GetWorks() []*WorkAssignment {
	if x != nil {
		return x.Works
	}
	return nil
}

func (x *GetWorksForAssistantResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetWorkDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        int32                  `protobuf:"varint,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkDetailsRequest) Reset() {
	*x = GetWorkDetailsRequest{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkDetailsRequest) ProtoMessage() {}

func (x *GetWorkDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetWorkDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{4}
}

func (x *GetWorkDetailsRequest) GetWorkId() int32 {
	if x != nil {
		return x.WorkId
	}
	return 0
}

type GetWorkDetailsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkId          int32                  `protobuf:"varint,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	TaskTitle       string                 `protobuf:"bytes,2,opt,name=task_title,json=taskTitle,proto3" json:"task_title,omitempty"`
	TaskDescription string                 `protobuf:"bytes,3,opt,name=task_description,json=taskDescription,proto3" json:"task_description,omitempty"`
	TaskDeadline    string                 `protobuf:"bytes,4,opt,name=task_deadline,json=taskDeadline,proto3" json:"task_deadline,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	ContentUrl      string                 `protobuf:"bytes,7,opt,name=content_url,json=contentUrl,proto3" json:"content_url,omitempty"`
	Error           string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetWorkDetailsResponse) Reset() {
	*x = GetWorkDetailsResponse{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkDetailsResponse) ProtoMessage() {}

func (x *GetWorkDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetWorkDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorkDetailsResponse) GetWorkId() int32 {
	if x != nil {
		return x.WorkId
	}
	return 0
}

func (x *GetWorkDetailsResponse) GetTaskTitle() string {
	if x != nil {
		return x.TaskTitle
	}
	return ""
}

func (x *GetWorkDetailsResponse) GetTaskDescription() string {
	if x != nil {
		return x.TaskDescription
	}
	return ""
}

func (x *GetWorkDetailsResponse) GetTaskDeadline() string {
	if x != nil {
		return x.TaskDeadline
	}
	return ""
}

func (x *GetWorkDetailsResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetWorkDetailsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetWorkDetailsResponse) GetContentUrl() string {
	if x != nil {
		return x.ContentUrl
	}
	return ""
}

func (x *GetWorkDetailsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WorkAssignment struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WorkId            int32                  `protobuf:"varint,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	TaskId            int32                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskTitle         string                 `protobuf:"bytes,3,opt,name=task_title,json=taskTitle,proto3" json:"task_title,omitempty"`
	StudentId         int32                  `protobuf:"varint,4,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StudentEmail      string                 `protobuf:"bytes,5,opt,name=student_email,json=studentEmail,proto3" json:"student_email,omitempty"`
	StudentName       string                 `protobuf:"bytes,6,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	StudentSurname    string                 `protobuf:"bytes,7,opt,name=student_surname,json=studentSurname,proto3" json:"student_surname,omitempty"`
	StudentPatronymic string                 `protobuf:"bytes,8,opt,name=student_patronymic,json=studentPatronymic,proto3" json:"student_patronymic,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WorkAssignment) Reset() {
	*x = WorkAssignment{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkAssignment) ProtoMessage() {}

func (x *WorkAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkAssignment.ProtoReflect.Descriptor instead.
func (*WorkAssignment) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{6}
}

func (x *WorkAssignment) GetWorkId() int32 {
	if x != nil {
		return x.WorkId
	}
	return 0
}

func (x *WorkAssignment) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *WorkAssignment) GetTaskTitle() string {
	if x != nil {
		return x.TaskTitle
	}
	return ""
}

func (x *WorkAssignment) GetStudentId() int32 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *WorkAssignment) GetStudentEmail() string {
	if x != nil {
		return x.StudentEmail
	}
	return ""
}

func (x *WorkAssignment) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *WorkAssignment) GetStudentSurname() string {
	if x != nil {
		return x.StudentSurname
	}
	return ""
}

func (x *WorkAssignment) GetStudentPatronymic() string {
	if x != nil {
		return x.StudentPatronymic
	}
	return ""
}

type SubmitWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        int32                  `protobuf:"varint,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWorkRequest) Reset() {
	*x = SubmitWorkRequest{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWorkRequest) ProtoMessage() {}

func (x *SubmitWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWorkRequest.ProtoReflect.Descriptor instead.
func (*SubmitWorkRequest) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitWorkRequest) GetWorkId() int32 {
	if x != nil {
		return x.WorkId
	}
	return 0
}

func (x *SubmitWorkRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type SubmitWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWorkResponse) Reset() {
	*x = SubmitWorkResponse{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWorkResponse) ProtoMessage() {}

func (x *SubmitWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWorkResponse.ProtoReflect.Descriptor instead.
func (*SubmitWorkResponse) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitWorkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitWorkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetTaskDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`          // ID задания (tasks.id)
	StudentId     int32                  `protobuf:"varint,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"` // ID студента (users.id)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskDetailsRequest) Reset() {
	*x = GetTaskDetailsRequest{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskDetailsRequest) ProtoMessage() {}

func (x *GetTaskDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetTaskDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{9}
}

func (x *GetTaskDetailsRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *GetTaskDetailsRequest) GetStudentId() int32 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

type CriteriaGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // ID группы критериев (criteria_groups.id)
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                // Название группы (criteria_groups.group_name)
	IsBlocking    bool                   `protobuf:"varint,3,opt,name=is_blocking,json=isBlocking,proto3" json:"is_blocking,omitempty"` // Флаг блокировки (criteria_groups.block_flag)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CriteriaGroup) Reset() {
	*x = CriteriaGroup{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriteriaGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriteriaGroup) ProtoMessage() {}

func (x *CriteriaGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriteriaGroup.ProtoReflect.Descriptor instead.
func (*CriteriaGroup) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{10}
}

func (x *CriteriaGroup) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CriteriaGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CriteriaGroup) GetIsBlocking() bool {
	if x != nil {
		return x.IsBlocking
	}
	return false
}

type GetTaskDetailsResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TaskId                 int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                                                  // ID задания (tasks.id)
	TaskTitle              string                 `protobuf:"bytes,2,opt,name=task_title,json=taskTitle,proto3" json:"task_title,omitempty"`                                          // Название задания (tasks.title)
	TaskDescription        string                 `protobuf:"bytes,3,opt,name=task_description,json=taskDescription,proto3" json:"task_description,omitempty"`                        // Описание задания (tasks.description)
	TaskDeadline           string                 `protobuf:"bytes,4,opt,name=task_deadline,json=taskDeadline,proto3" json:"task_deadline,omitempty"`                                 // Дедлайн задания (tasks.deadline)
	TaskContentUrl         string                 `protobuf:"bytes,5,opt,name=task_content_url,json=taskContentUrl,proto3" json:"task_content_url,omitempty"`                         // Ссылка на материалы (tasks.content_url)
	MainCriteriaGroups     []*CriteriaGroup       `protobuf:"bytes,6,rep,name=main_criteria_groups,json=mainCriteriaGroups,proto3" json:"main_criteria_groups,omitempty"`             // Основные группы критериев
	BlockingCriteriaGroups []*CriteriaGroup       `protobuf:"bytes,7,rep,name=blocking_criteria_groups,json=blockingCriteriaGroups,proto3" json:"blocking_criteria_groups,omitempty"` // Блокирующие группы критериев
	Error                  string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`                                                                   // Сообщение об ошибке, если есть
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetTaskDetailsResponse) Reset() {
	*x = GetTaskDetailsResponse{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskDetailsResponse) ProtoMessage() {}

func (x *GetTaskDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetTaskDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{11}
}

func (x *GetTaskDetailsResponse) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *GetTaskDetailsResponse) GetTaskTitle() string {
	if x != nil {
		return x.TaskTitle
	}
	return ""
}

func (x *GetTaskDetailsResponse) GetTaskDescription() string {
	if x != nil {
		return x.TaskDescription
	}
	return ""
}

func (x *GetTaskDetailsResponse) GetTaskDeadline() string {
	if x != nil {
		return x.TaskDeadline
	}
	return ""
}

func (x *GetTaskDetailsResponse) GetTaskContentUrl() string {
	if x != nil {
		return x.TaskContentUrl
	}
	return ""
}

func (x *GetTaskDetailsResponse) GetMainCriteriaGroups() []*CriteriaGroup {
	if x != nil {
		return x.MainCriteriaGroups
	}
	return nil
}

func (x *GetTaskDetailsResponse) GetBlockingCriteriaGroups() []*CriteriaGroup {
	if x != nil {
		return x.BlockingCriteriaGroups
	}
	return nil
}

func (x *GetTaskDetailsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     int32                  `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"` // ID студента (users.id)
	TaskId        int32                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`          // ID задания (tasks.id)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkRequest) Reset() {
	*x = CreateWorkRequest{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkRequest) ProtoMessage() {}

func (x *CreateWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkRequest) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{12}
}

func (x *CreateWorkRequest) GetStudentId() int32 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *CreateWorkRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type CreateWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        int32                  `protobuf:"varint,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"` // ID созданной работы (student_works.id)
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                  // Сообщение об ошибке, если есть
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkResponse) Reset() {
	*x = CreateWorkResponse{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkResponse) ProtoMessage() {}

func (x *CreateWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkResponse) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{13}
}

func (x *CreateWorkResponse) GetWorkId() int32 {
	if x != nil {
		return x.WorkId
	}
	return 0
}

func (x *CreateWorkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CheckExistingWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     int32                  `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"` // ID студента (users.id)
	TaskId        int32                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`          // ID задания (tasks.id)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckExistingWorkRequest) Reset() {
	*x = CheckExistingWorkRequest{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckExistingWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExistingWorkRequest) ProtoMessage() {}

func (x *CheckExistingWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExistingWorkRequest.ProtoReflect.Descriptor instead.
func (*CheckExistingWorkRequest) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{14}
}

func (x *CheckExistingWorkRequest) GetStudentId() int32 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *CheckExistingWorkRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type CheckExistingWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`                        // Существует ли работа
	WorkId        int32                  `protobuf:"varint,2,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`          // ID работы, если существует
	StudentId     int32                  `protobuf:"varint,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"` // ID студента для проверки
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                           // Сообщение об ошибке, если есть
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckExistingWorkResponse) Reset() {
	*x = CheckExistingWorkResponse{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckExistingWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExistingWorkResponse) ProtoMessage() {}

func (x *CheckExistingWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExistingWorkResponse.ProtoReflect.Descriptor instead.
func (*CheckExistingWorkResponse) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{15}
}

func (x *CheckExistingWorkResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *CheckExistingWorkResponse) GetWorkId() int32 {
	if x != nil {
		return x.WorkId
	}
	return 0
}

func (x *CheckExistingWorkResponse) GetStudentId() int32 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *CheckExistingWorkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GenerateDownloadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        int32                  `protobuf:"varint,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDownloadURLRequest) Reset() {
	*x = GenerateDownloadURLRequest{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDownloadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDownloadURLRequest) ProtoMessage() {}

func (x *GenerateDownloadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDownloadURLRequest.ProtoReflect.Descriptor instead.
func (*GenerateDownloadURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{16}
}

func (x *GenerateDownloadURLRequest) GetWorkId() int32 {
	if x != nil {
		return x.WorkId
	}
	return 0
}

type GenerateDownloadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDownloadURLResponse) Reset() {
	*x = GenerateDownloadURLResponse{}
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDownloadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDownloadURLResponse) ProtoMessage() {}

func (x *GenerateDownloadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workassignment_workassignment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDownloadURLResponse.ProtoReflect.Descriptor instead.
func (*GenerateDownloadURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_workassignment_workassignment_proto_rawDescGZIP(), []int{17}
}

func (x *GenerateDownloadURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GenerateDownloadURLResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_workassignment_workassignment_proto protoreflect.FileDescriptor

const file_proto_workassignment_workassignment_proto_rawDesc = "" +
	"\n" +
	")proto/workassignment/workassignment.proto\x12\x0eworkassignment\"P\n" +
	"\x18GenerateUploadURLRequest\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\x05R\x06workId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\"C\n" +
	"\x19GenerateUploadURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"@\n" +
	"\x1bGetWorksForAssistantRequest\x12!\n" +
	"\fassistant_id\x18\x01 \x01(\x05R\vassistantId\"j\n" +
	"\x1cGetWorksForAssistantResponse\x124\n" +
	"\x05works\x18\x01 \x03(\v2\x1e.workassignment.WorkAssignmentR\x05works\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"0\n" +
	"\x15GetWorkDetailsRequest\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\x05R\x06workId\"\x8e\x02\n" +
	"\x16GetWorkDetailsResponse\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\x05R\x06workId\x12\x1d\n" +
	"\n" +
	"task_title\x18\x02 \x01(\tR\ttaskTitle\x12)\n" +
	"\x10task_description\x18\x03 \x01(\tR\x0ftaskDescription\x12#\n" +
	"\rtask_deadline\x18\x04 \x01(\tR\ftaskDeadline\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1f\n" +
	"\vcontent_url\x18\a \x01(\tR\n" +
	"contentUrl\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"\xa0\x02\n" +
	"\x0eWorkAssignment\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\x05R\x06workId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x05R\x06taskId\x12\x1d\n" +
	"\n" +
	"task_title\x18\x03 \x01(\tR\ttaskTitle\x12\x1d\n" +
	"\n" +
	"student_id\x18\x04 \x01(\x05R\tstudentId\x12#\n" +
	"\rstudent_email\x18\x05 \x01(\tR\fstudentEmail\x12!\n" +
	"\fstudent_name\x18\x06 \x01(\tR\vstudentName\x12'\n" +
	"\x0fstudent_surname\x18\a \x01(\tR\x0estudentSurname\x12-\n" +
	"\x12student_patronymic\x18\b \x01(\tR\x11studentPatronymic\"I\n" +
	"\x11SubmitWorkRequest\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\x05R\x06workId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\"D\n" +
	"\x12SubmitWorkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"O\n" +
	"\x15GetTaskDetailsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\x05R\tstudentId\"T\n" +
	"\rCriteriaGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vis_blocking\x18\x03 \x01(\bR\n" +
	"isBlocking\"\x8a\x03\n" +
	"\x16GetTaskDetailsResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12\x1d\n" +
	"\n" +
	"task_title\x18\x02 \x01(\tR\ttaskTitle\x12)\n" +
	"\x10task_description\x18\x03 \x01(\tR\x0ftaskDescription\x12#\n" +
	"\rtask_deadline\x18\x04 \x01(\tR\ftaskDeadline\x12(\n" +
	"\x10task_content_url\x18\x05 \x01(\tR\x0etaskContentUrl\x12O\n" +
	"\x14main_criteria_groups\x18\x06 \x03(\v2\x1d.workassignment.CriteriaGroupR\x12mainCriteriaGroups\x12W\n" +
	"\x18blocking_criteria_groups\x18\a \x03(\v2\x1d.workassignment.CriteriaGroupR\x16blockingCriteriaGroups\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"K\n" +
	"\x11CreateWorkRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\x05R\tstudentId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x05R\x06taskId\"C\n" +
	"\x12CreateWorkResponse\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\x05R\x06workId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"R\n" +
	"\x18CheckExistingWorkRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\x05R\tstudentId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x05R\x06taskId\"\x81\x01\n" +
	"\x19CheckExistingWorkResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x17\n" +
	"\awork_id\x18\x02 \x01(\x05R\x06workId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\x05R\tstudentId\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"5\n" +
	"\x1aGenerateDownloadURLRequest\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\x05R\x06workId\"E\n" +
	"\x1bGenerateDownloadURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xba\x06\n" +
	"\x15WorkAssignmentService\x12q\n" +
	"\x14GetWorksForAssistant\x12+.workassignment.GetWorksForAssistantRequest\x1a,.workassignment.GetWorksForAssistantResponse\x12_\n" +
	"\x0eGetWorkDetails\x12%.workassignment.GetWorkDetailsRequest\x1a&.workassignment.GetWorkDetailsResponse\x12S\n" +
	"\n" +
	"SubmitWork\x12!.workassignment.SubmitWorkRequest\x1a\".workassignment.SubmitWorkResponse\x12_\n" +
	"\x0eGetTaskDetails\x12%.workassignment.GetTaskDetailsRequest\x1a&.workassignment.GetTaskDetailsResponse\x12n\n" +
	"\x13GenerateDownloadURL\x12*.workassignment.GenerateDownloadURLRequest\x1a+.workassignment.GenerateDownloadURLResponse\x12S\n" +
	"\n" +
	"CreateWork\x12!.workassignment.CreateWorkRequest\x1a\".workassignment.CreateWorkResponse\x12h\n" +
	"\x11CheckExistingWork\x12(.workassignment.CheckExistingWorkRequest\x1a).workassignment.CheckExistingWorkResponse\x12h\n" +
	"\x11GenerateUploadURL\x12(.workassignment.GenerateUploadURLRequest\x1a).workassignment.GenerateUploadURLResponseB'Z%./proto/workassignment;workassignmentb\x06proto3"

var (
	file_proto_workassignment_workassignment_proto_rawDescOnce sync.Once
	file_proto_workassignment_workassignment_proto_rawDescData []byte
)

func file_proto_workassignment_workassignment_proto_rawDescGZIP() []byte {
	file_proto_workassignment_workassignment_proto_rawDescOnce.Do(func() {
		file_proto_workassignment_workassignment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_workassignment_workassignment_proto_rawDesc), len(file_proto_workassignment_workassignment_proto_rawDesc)))
	})
	return file_proto_workassignment_workassignment_proto_rawDescData
}

var file_proto_workassignment_workassignment_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_workassignment_workassignment_proto_goTypes = []any{
	(*GenerateUploadURLRequest)(nil),     // 0: workassignment.GenerateUploadURLRequest
	(*GenerateUploadURLResponse)(nil),    // 1: workassignment.GenerateUploadURLResponse
	(*GetWorksForAssistantRequest)(nil),  // 2: workassignment.GetWorksForAssistantRequest
	(*GetWorksForAssistantResponse)(nil), // 3: workassignment.GetWorksForAssistantResponse
	(*GetWorkDetailsRequest)(nil),        // 4: workassignment.GetWorkDetailsRequest
	(*GetWorkDetailsResponse)(nil),       // 5: workassignment.GetWorkDetailsResponse
	(*WorkAssignment)(nil),               // 6: workassignment.WorkAssignment
	(*SubmitWorkRequest)(nil),            // 7: workassignment.SubmitWorkRequest
	(*SubmitWorkResponse)(nil),           // 8: workassignment.SubmitWorkResponse
	(*GetTaskDetailsRequest)(nil),        // 9: workassignment.GetTaskDetailsRequest
	(*CriteriaGroup)(nil),                // 10: workassignment.CriteriaGroup
	(*GetTaskDetailsResponse)(nil),       // 11: workassignment.GetTaskDetailsResponse
	(*CreateWorkRequest)(nil),            // 12: workassignment.CreateWorkRequest
	(*CreateWorkResponse)(nil),           // 13: workassignment.CreateWorkResponse
	(*CheckExistingWorkRequest)(nil),     // 14: workassignment.CheckExistingWorkRequest
	(*CheckExistingWorkResponse)(nil),    // 15: workassignment.CheckExistingWorkResponse
	(*GenerateDownloadURLRequest)(nil),   // 16: workassignment.GenerateDownloadURLRequest
	(*GenerateDownloadURLResponse)(nil),  // 17: workassignment.GenerateDownloadURLResponse
}
var file_proto_workassignment_workassignment_proto_depIdxs = []int32{
	6,  // 0: workassignment.GetWorksForAssistantResponse.works:type_name -> workassignment.WorkAssignment
	10, // 1: workassignment.GetTaskDetailsResponse.main_criteria_groups:type_name -> workassignment.CriteriaGroup
	10, // 2: workassignment.GetTaskDetailsResponse.blocking_criteria_groups:type_name -> workassignment.CriteriaGroup
	2,  // 3: workassignment.WorkAssignmentService.GetWorksForAssistant:input_type -> workassignment.GetWorksForAssistantRequest
	4,  // 4: workassignment.WorkAssignmentService.GetWorkDetails:input_type -> workassignment.GetWorkDetailsRequest
	7,  // 5: workassignment.WorkAssignmentService.SubmitWork:input_type -> workassignment.SubmitWorkRequest
	9,  // 6: workassignment.WorkAssignmentService.GetTaskDetails:input_type -> workassignment.GetTaskDetailsRequest
	16, // 7: workassignment.WorkAssignmentService.GenerateDownloadURL:input_type -> workassignment.GenerateDownloadURLRequest
	12, // 8: workassignment.WorkAssignmentService.CreateWork:input_type -> workassignment.CreateWorkRequest
	14, // 9: workassignment.WorkAssignmentService.CheckExistingWork:input_type -> workassignment.CheckExistingWorkRequest
	0,  // 10: workassignment.WorkAssignmentService.GenerateUploadURL:input_type -> workassignment.GenerateUploadURLRequest
	3,  // 11: workassignment.WorkAssignmentService.GetWorksForAssistant:output_type -> workassignment.GetWorksForAssistantResponse
	5,  // 12: workassignment.WorkAssignmentService.GetWorkDetails:output_type -> workassignment.GetWorkDetailsResponse
	8,  // 13: workassignment.WorkAssignmentService.SubmitWork:output_type -> workassignment.SubmitWorkResponse
	11, // 14: workassignment.WorkAssignmentService.GetTaskDetails:output_type -> workassignment.GetTaskDetailsResponse
	17, // 15: workassignment.WorkAssignmentService.GenerateDownloadURL:output_type -> workassignment.GenerateDownloadURLResponse
	13, // 16: workassignment.WorkAssignmentService.CreateWork:output_type -> workassignment.CreateWorkResponse
	15, // 17: workassignment.WorkAssignmentService.CheckExistingWork:output_type -> workassignment.CheckExistingWorkResponse
	1,  // 18: workassignment.WorkAssignmentService.GenerateUploadURL:output_type -> workassignment.GenerateUploadURLResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_workassignment_workassignment_proto_init() }
func file_proto_workassignment_workassignment_proto_init() {
	if File_proto_workassignment_workassignment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_workassignment_workassignment_proto_rawDesc), len(file_proto_workassignment_workassignment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_workassignment_workassignment_proto_goTypes,
		DependencyIndexes: file_proto_workassignment_workassignment_proto_depIdxs,
		MessageInfos:      file_proto_workassignment_workassignment_proto_msgTypes,
	}.Build()
	File_proto_workassignment_workassignment_proto = out.File
	file_proto_workassignment_workassignment_proto_goTypes = nil
	file_proto_workassignment_workassignment_proto_depIdxs = nil
}
